name: lagrange-website
channels:
  - conda-forge
dependencies:
  - python=3.11
  - doxygen=1.9.4
  - ghp-import=2.1.0
  - mkdocs-exclude=1.0.2
  - mkdocs-macros-plugin=0.7.0
  - mkdocs=1.4.2
  - pygments=2.14.0
  - pymdown-extensions=9.9.2
  - pypandoc=1.10
  - pystache=0.5.4
  - pip=23.0
  - pip:
    - mkdocs-material==9.0.11 # conda recipe is broken...
    - LinkChecker==10.2.1
    - mkdocs-bibtex==2.8.12
    - mkdocs-img2figv2-plugin==0.0.2
    - mkdocs-redirects==1.2.0
