name: lagrange-website
channels:
  - conda-forge
dependencies:
  - python=3.10
  - doxygen=1.9.2
  - ghp-import=2.0.2
  - mkdocs-exclude=1.0.2
  - mkdocs-macros-plugin=0.7.0
  - mkdocs-material=8.2.11
  - mkdocs=1.2.4
  - pygments=2.11.2
  - pymdown-extensions=9.3
  - pystache=0.5.4
  - pypandoc=1.10
  - pip=22.0.4
  - pip:
      - mkdocs-redirects==1.0.3
      - gitchangelog==3.0.4
      - LinkChecker==10.1.0
      - mkdocs-bibtex==2.8.5
      - mkdocs-img2figv2-plugin==0.0.2
