var annotated_dup =
[
    [ "lagrange", "namespacelagrange.html", [
      [ "bvh", null, [
        [ "AABB", "classlagrange_1_1bvh_1_1_a_a_b_b.html", "classlagrange_1_1bvh_1_1_a_a_b_b" ],
        [ "AABBIGL", "classlagrange_1_1bvh_1_1_a_a_b_b_i_g_l.html", "classlagrange_1_1bvh_1_1_a_a_b_b_i_g_l" ],
        [ "BVH", "classlagrange_1_1bvh_1_1_b_v_h.html", "classlagrange_1_1bvh_1_1_b_v_h" ],
        [ "BVHNanoflann", "classlagrange_1_1bvh_1_1_b_v_h_nanoflann.html", "classlagrange_1_1bvh_1_1_b_v_h_nanoflann" ],
        [ "EdgeAABBTree", "structlagrange_1_1bvh_1_1_edge_a_a_b_b_tree.html", "structlagrange_1_1bvh_1_1_edge_a_a_b_b_tree" ],
        [ "MeshDistancesOptions", "structlagrange_1_1bvh_1_1_mesh_distances_options.html", "structlagrange_1_1bvh_1_1_mesh_distances_options" ],
        [ "PyEdgeAABBTree", "classlagrange_1_1bvh_1_1_py_edge_a_a_b_b_tree.html", null ],
        [ "ResolveTJunctionsOptions", "structlagrange_1_1bvh_1_1_resolve_t_junctions_options.html", "structlagrange_1_1bvh_1_1_resolve_t_junctions_options" ],
        [ "TriangleAABBTree", "classlagrange_1_1bvh_1_1_triangle_a_a_b_b_tree.html", "classlagrange_1_1bvh_1_1_triangle_a_a_b_b_tree" ],
        [ "UVOverlapOptions", "structlagrange_1_1bvh_1_1_u_v_overlap_options.html", "structlagrange_1_1bvh_1_1_u_v_overlap_options" ],
        [ "UVOverlapResult", "structlagrange_1_1bvh_1_1_u_v_overlap_result.html", "structlagrange_1_1bvh_1_1_u_v_overlap_result" ],
        [ "WeldOptions", "structlagrange_1_1bvh_1_1_weld_options.html", "structlagrange_1_1bvh_1_1_weld_options" ]
      ] ],
      [ "experimental", null, [
        [ "internal", null, [
          [ "ArraySerialization", "structlagrange_1_1experimental_1_1internal_1_1_array_serialization.html", null ]
        ] ],
        [ "ArrayBase", "classlagrange_1_1experimental_1_1_array_base.html", "classlagrange_1_1experimental_1_1_array_base" ],
        [ "ArrayTypeInfo", "classlagrange_1_1experimental_1_1_array_type_info.html", null ],
        [ "Attribute", "classlagrange_1_1experimental_1_1_attribute.html", null ],
        [ "AttributeManager", "classlagrange_1_1experimental_1_1_attribute_manager.html", null ],
        [ "EigenArray", "classlagrange_1_1experimental_1_1_eigen_array.html", "classlagrange_1_1experimental_1_1_eigen_array" ],
        [ "EigenArrayRef", "classlagrange_1_1experimental_1_1_eigen_array_ref.html", null ],
        [ "EnumToScalar", "structlagrange_1_1experimental_1_1_enum_to_scalar.html", null ],
        [ "EnumToScalar< ScalarEnum::DOUBLE >", "structlagrange_1_1experimental_1_1_enum_to_scalar_3_01_scalar_enum_1_1_d_o_u_b_l_e_01_4.html", null ],
        [ "EnumToScalar< ScalarEnum::FLOAT >", "structlagrange_1_1experimental_1_1_enum_to_scalar_3_01_scalar_enum_1_1_f_l_o_a_t_01_4.html", null ],
        [ "EnumToScalar< ScalarEnum::INT16 >", "structlagrange_1_1experimental_1_1_enum_to_scalar_3_01_scalar_enum_1_1_i_n_t16_01_4.html", null ],
        [ "EnumToScalar< ScalarEnum::INT32 >", "structlagrange_1_1experimental_1_1_enum_to_scalar_3_01_scalar_enum_1_1_i_n_t32_01_4.html", null ],
        [ "EnumToScalar< ScalarEnum::INT64 >", "structlagrange_1_1experimental_1_1_enum_to_scalar_3_01_scalar_enum_1_1_i_n_t64_01_4.html", null ],
        [ "EnumToScalar< ScalarEnum::INT8 >", "structlagrange_1_1experimental_1_1_enum_to_scalar_3_01_scalar_enum_1_1_i_n_t8_01_4.html", null ],
        [ "EnumToScalar< ScalarEnum::UINT16 >", "structlagrange_1_1experimental_1_1_enum_to_scalar_3_01_scalar_enum_1_1_u_i_n_t16_01_4.html", null ],
        [ "EnumToScalar< ScalarEnum::UINT32 >", "structlagrange_1_1experimental_1_1_enum_to_scalar_3_01_scalar_enum_1_1_u_i_n_t32_01_4.html", null ],
        [ "EnumToScalar< ScalarEnum::UINT64 >", "structlagrange_1_1experimental_1_1_enum_to_scalar_3_01_scalar_enum_1_1_u_i_n_t64_01_4.html", null ],
        [ "EnumToScalar< ScalarEnum::UINT8 >", "structlagrange_1_1experimental_1_1_enum_to_scalar_3_01_scalar_enum_1_1_u_i_n_t8_01_4.html", null ],
        [ "IndexedAttribute", "classlagrange_1_1experimental_1_1_indexed_attribute.html", null ],
        [ "IndexedAttributeManager", "classlagrange_1_1experimental_1_1_indexed_attribute_manager.html", null ],
        [ "RawArray", "classlagrange_1_1experimental_1_1_raw_array.html", null ],
        [ "ScalarToEnum", "structlagrange_1_1experimental_1_1_scalar_to_enum.html", null ],
        [ "ScalarToEnum< double, void >", "structlagrange_1_1experimental_1_1_scalar_to_enum_3_01double_00_01void_01_4.html", null ],
        [ "ScalarToEnum< float, void >", "structlagrange_1_1experimental_1_1_scalar_to_enum_3_01float_00_01void_01_4.html", null ],
        [ "ScalarToEnum< int16_t, void >", "structlagrange_1_1experimental_1_1_scalar_to_enum_3_01int16__t_00_01void_01_4.html", null ],
        [ "ScalarToEnum< int32_t, void >", "structlagrange_1_1experimental_1_1_scalar_to_enum_3_01int32__t_00_01void_01_4.html", null ],
        [ "ScalarToEnum< int64_t, void >", "structlagrange_1_1experimental_1_1_scalar_to_enum_3_01int64__t_00_01void_01_4.html", null ],
        [ "ScalarToEnum< int8_t, void >", "structlagrange_1_1experimental_1_1_scalar_to_enum_3_01int8__t_00_01void_01_4.html", null ],
        [ "ScalarToEnum< uint16_t, void >", "structlagrange_1_1experimental_1_1_scalar_to_enum_3_01uint16__t_00_01void_01_4.html", null ],
        [ "ScalarToEnum< uint32_t, void >", "structlagrange_1_1experimental_1_1_scalar_to_enum_3_01uint32__t_00_01void_01_4.html", null ],
        [ "ScalarToEnum< uint64_t, void >", "structlagrange_1_1experimental_1_1_scalar_to_enum_3_01uint64__t_00_01void_01_4.html", null ],
        [ "ScalarToEnum< uint8_t, void >", "structlagrange_1_1experimental_1_1_scalar_to_enum_3_01uint8__t_00_01void_01_4.html", null ]
      ] ],
      [ "filtering", null, [
        [ "threadpool", null, [
          [ "ThreadPool", "structlagrange_1_1filtering_1_1threadpool_1_1_thread_pool.html", null ]
        ] ],
        [ "AttributeSmoothingOptions", "structlagrange_1_1filtering_1_1_attribute_smoothing_options.html", "structlagrange_1_1filtering_1_1_attribute_smoothing_options" ],
        [ "SmoothingOptions", "structlagrange_1_1filtering_1_1_smoothing_options.html", "structlagrange_1_1filtering_1_1_smoothing_options" ]
      ] ],
      [ "geodesic", null, [
        [ "GeodesicEngine", "classlagrange_1_1geodesic_1_1_geodesic_engine.html", "classlagrange_1_1geodesic_1_1_geodesic_engine" ],
        [ "GeodesicEngineDGPC", "classlagrange_1_1geodesic_1_1_geodesic_engine_d_g_p_c.html", "classlagrange_1_1geodesic_1_1_geodesic_engine_d_g_p_c" ],
        [ "GeodesicEngineHeat", "classlagrange_1_1geodesic_1_1_geodesic_engine_heat.html", "classlagrange_1_1geodesic_1_1_geodesic_engine_heat" ],
        [ "GeodesicEngineMMP", "classlagrange_1_1geodesic_1_1_geodesic_engine_m_m_p.html", "classlagrange_1_1geodesic_1_1_geodesic_engine_m_m_p" ],
        [ "GeodesicPathResult", "structlagrange_1_1geodesic_1_1_geodesic_path_result.html", "structlagrange_1_1geodesic_1_1_geodesic_path_result" ],
        [ "PointToPointGeodesicOptions", "structlagrange_1_1geodesic_1_1_point_to_point_geodesic_options.html", "structlagrange_1_1geodesic_1_1_point_to_point_geodesic_options" ],
        [ "PointToPointGeodesicPathOptions", "structlagrange_1_1geodesic_1_1_point_to_point_geodesic_path_options.html", "structlagrange_1_1geodesic_1_1_point_to_point_geodesic_path_options" ],
        [ "SingleSourceGeodesicOptions", "structlagrange_1_1geodesic_1_1_single_source_geodesic_options.html", "structlagrange_1_1geodesic_1_1_single_source_geodesic_options" ],
        [ "SingleSourceGeodesicResult", "structlagrange_1_1geodesic_1_1_single_source_geodesic_result.html", "structlagrange_1_1geodesic_1_1_single_source_geodesic_result" ]
      ] ],
      [ "image", "namespacelagrange_1_1image.html", [
        [ "convert_image_pixel", "structlagrange_1_1image_1_1convert__image__pixel.html", null ],
        [ "ImageHistogram", "structlagrange_1_1image_1_1_image_histogram.html", "structlagrange_1_1image_1_1_image_histogram" ],
        [ "ImageStorage", "classlagrange_1_1image_1_1_image_storage.html", null ],
        [ "ImageTraits", "structlagrange_1_1image_1_1_image_traits.html", null ],
        [ "ImageView", "classlagrange_1_1image_1_1_image_view.html", null ],
        [ "ImageViewBase", "classlagrange_1_1image_1_1_image_view_base.html", null ],
        [ "RawInputImage", "classlagrange_1_1image_1_1_raw_input_image.html", "classlagrange_1_1image_1_1_raw_input_image" ]
      ] ],
      [ "image_io", null, [
        [ "LoadImageResult", "structlagrange_1_1image__io_1_1_load_image_result.html", null ],
        [ "SVGSetting", "structlagrange_1_1image__io_1_1_s_v_g_setting.html", "structlagrange_1_1image__io_1_1_s_v_g_setting" ]
      ] ],
      [ "internal", "namespacelagrange_1_1internal.html", [
        [ "AttributeInfo", "structlagrange_1_1internal_1_1_attribute_info.html", "structlagrange_1_1internal_1_1_attribute_info" ],
        [ "BucketSortOffset", "structlagrange_1_1internal_1_1_bucket_sort_offset.html", "structlagrange_1_1internal_1_1_bucket_sort_offset" ],
        [ "BucketSortResult", "structlagrange_1_1internal_1_1_bucket_sort_result.html", "structlagrange_1_1internal_1_1_bucket_sort_result" ],
        [ "CheckAttributeResult", "structlagrange_1_1internal_1_1_check_attribute_result.html", "structlagrange_1_1internal_1_1_check_attribute_result" ],
        [ "control_block", "classlagrange_1_1internal_1_1control__block.html", null ],
        [ "control_block_base", "classlagrange_1_1internal_1_1control__block__base.html", null ],
        [ "default_delete", "classlagrange_1_1internal_1_1default__delete.html", "classlagrange_1_1internal_1_1default__delete" ],
        [ "default_delete< T[]>", "classlagrange_1_1internal_1_1default__delete_3_01_t_0f_0e_4.html", "classlagrange_1_1internal_1_1default__delete_3_01_t_0f_0e_4" ],
        [ "DijkstraCache", "structlagrange_1_1internal_1_1_dijkstra_cache.html", null ],
        [ "DijkstraOptions", "structlagrange_1_1internal_1_1_dijkstra_options.html", "structlagrange_1_1internal_1_1_dijkstra_options" ],
        [ "InverseMapping", "structlagrange_1_1internal_1_1_inverse_mapping.html", "structlagrange_1_1internal_1_1_inverse_mapping" ],
        [ "MapAttributesOptions", "structlagrange_1_1internal_1_1_map_attributes_options.html", "structlagrange_1_1internal_1_1_map_attributes_options" ],
        [ "ptr", "classlagrange_1_1internal_1_1ptr.html", null ],
        [ "shared_ptr", "classlagrange_1_1internal_1_1shared__ptr.html", "classlagrange_1_1internal_1_1shared__ptr" ],
        [ "shared_ptr_access", "classlagrange_1_1internal_1_1shared__ptr__access.html", "classlagrange_1_1internal_1_1shared__ptr__access" ],
        [ "shared_ptr_access< T, false, true >", "classlagrange_1_1internal_1_1shared__ptr__access_3_01_t_00_01false_00_01true_01_4.html", "classlagrange_1_1internal_1_1shared__ptr__access_3_01_t_00_01false_00_01true_01_4" ],
        [ "shared_ptr_access< T, true, false >", "classlagrange_1_1internal_1_1shared__ptr__access_3_01_t_00_01true_00_01false_01_4.html", "classlagrange_1_1internal_1_1shared__ptr__access_3_01_t_00_01true_00_01false_01_4" ],
        [ "SkinningExtractNResult", "structlagrange_1_1internal_1_1_skinning_extract_n_result.html", "structlagrange_1_1internal_1_1_skinning_extract_n_result" ],
        [ "SurfaceMeshInfo", "structlagrange_1_1internal_1_1_surface_mesh_info.html", "structlagrange_1_1internal_1_1_surface_mesh_info" ],
        [ "UnorientedEdge", "structlagrange_1_1internal_1_1_unoriented_edge.html", null ],
        [ "UVScalarTag", "structlagrange_1_1internal_1_1_u_v_scalar_tag.html", null ],
        [ "weak_ptr", "classlagrange_1_1internal_1_1weak__ptr.html", "classlagrange_1_1internal_1_1weak__ptr" ]
      ] ],
      [ "io", "namespacelagrange_1_1io.html", [
        [ "internal", null, [
          [ "ObjReaderResult", "structlagrange_1_1io_1_1internal_1_1_obj_reader_result.html", "structlagrange_1_1io_1_1internal_1_1_obj_reader_result" ]
        ] ],
        [ "legacy", null, [
          [ "MeshLoaderParams", "structlagrange_1_1io_1_1legacy_1_1_mesh_loader_params.html", "structlagrange_1_1io_1_1legacy_1_1_mesh_loader_params" ],
          [ "MeshLoaderResult", "structlagrange_1_1io_1_1legacy_1_1_mesh_loader_result.html", null ]
        ] ],
        [ "LoadOptions", "structlagrange_1_1io_1_1_load_options.html", "structlagrange_1_1io_1_1_load_options" ],
        [ "SaveOptions", "structlagrange_1_1io_1_1_save_options.html", "structlagrange_1_1io_1_1_save_options" ]
      ] ],
      [ "legacy", null, [
        [ "BackwardMeshMapping", "structlagrange_1_1legacy_1_1_backward_mesh_mapping.html", null ],
        [ "Components", "classlagrange_1_1legacy_1_1_components.html", null ],
        [ "ComputeBorderedComponentsOutput", "structlagrange_1_1legacy_1_1_compute_bordered_components_output.html", null ],
        [ "ComputeMeshCentroidOutput", "structlagrange_1_1legacy_1_1_compute_mesh_centroid_output.html", null ],
        [ "ComputePointcloudPCAOutput", "structlagrange_1_1legacy_1_1_compute_pointcloud_p_c_a_output.html", null ],
        [ "ForwardMeshMapping", "structlagrange_1_1legacy_1_1_forward_mesh_mapping.html", null ],
        [ "GeometricProfile", "structlagrange_1_1legacy_1_1_geometric_profile.html", null ],
        [ "MarchingTrianglesOutput", "structlagrange_1_1legacy_1_1_marching_triangles_output.html", null ],
        [ "MeshMapping", "structlagrange_1_1legacy_1_1_mesh_mapping.html", null ],
        [ "MeshTopology", "classlagrange_1_1legacy_1_1_mesh_topology.html", null ],
        [ "SelectFacetsByNormalSimilarityParameters", "structlagrange_1_1legacy_1_1_select_facets_by_normal_similarity_parameters.html", null ],
        [ "SubdividedMeshData", "structlagrange_1_1legacy_1_1_subdivided_mesh_data.html", null ]
      ] ],
      [ "mapbox", null, [
        [ "detail", null, [
          [ "Earcut", "classlagrange_1_1mapbox_1_1detail_1_1_earcut.html", null ]
        ] ],
        [ "util", null, [
          [ "nth", "structlagrange_1_1mapbox_1_1util_1_1nth.html", null ]
        ] ]
      ] ],
      [ "MeshTraitHelper", null, [
        [ "is_mesh_helper", "structlagrange_1_1_mesh_trait_helper_1_1is__mesh__helper.html", null ],
        [ "is_mesh_helper< MeshType, typename Void< typename MeshType::VertexArray, typename MeshType::FacetArray >::type >", "structlagrange_1_1_mesh_trait_helper_1_1is__mesh__helper_3_01_mesh_type_00_01typename_01_void_3_189721d847f0585e54612704ceb864c0.html", null ],
        [ "is_mesh_smart_ptr_helper", "structlagrange_1_1_mesh_trait_helper_1_1is__mesh__smart__ptr__helper.html", null ],
        [ "is_mesh_smart_ptr_helper< MeshTypePtr, typename Void< typename MeshTypePtr::element_type, typename MeshTypePtr::element_type::VertexArray, typename MeshTypePtr::element_type::FacetArray >::type >", "structlagrange_1_1_mesh_trait_helper_1_1is__mesh__smart__ptr__helper_3_01_mesh_type_ptr_00_01typdd3a1b441f06e428de34247e1df62704.html", null ],
        [ "Void", "structlagrange_1_1_mesh_trait_helper_1_1_void.html", null ]
      ] ],
      [ "packing", null, [
        [ "legacy", null, [
          [ "PackingFailure", "classlagrange_1_1packing_1_1legacy_1_1_packing_failure.html", null ],
          [ "PackingOptions", "structlagrange_1_1packing_1_1legacy_1_1_packing_options.html", "structlagrange_1_1packing_1_1legacy_1_1_packing_options" ]
        ] ],
        [ "PackingFailure", "classlagrange_1_1packing_1_1_packing_failure.html", null ],
        [ "RepackOptions", "structlagrange_1_1packing_1_1_repack_options.html", "structlagrange_1_1packing_1_1_repack_options" ]
      ] ],
      [ "poisson", null, [
        [ "threadpool", null, [
          [ "ThreadPool", "structlagrange_1_1poisson_1_1threadpool_1_1_thread_pool.html", null ]
        ] ],
        [ "AttributeEvaluator", "classlagrange_1_1poisson_1_1_attribute_evaluator.html", "classlagrange_1_1poisson_1_1_attribute_evaluator" ],
        [ "CommonOptions", "structlagrange_1_1poisson_1_1_common_options.html", "structlagrange_1_1poisson_1_1_common_options" ],
        [ "EvaluatorOptions", "structlagrange_1_1poisson_1_1_evaluator_options.html", "structlagrange_1_1poisson_1_1_evaluator_options" ],
        [ "ReconstructionOptions", "structlagrange_1_1poisson_1_1_reconstruction_options.html", "structlagrange_1_1poisson_1_1_reconstruction_options" ]
      ] ],
      [ "polyddg", null, [
        [ "DifferentialOperators", "classlagrange_1_1polyddg_1_1_differential_operators.html", "classlagrange_1_1polyddg_1_1_differential_operators" ],
        [ "HodgeDecompositionOptions", "structlagrange_1_1polyddg_1_1_hodge_decomposition_options.html", "structlagrange_1_1polyddg_1_1_hodge_decomposition_options" ],
        [ "HodgeDecompositionResult", "structlagrange_1_1polyddg_1_1_hodge_decomposition_result.html", "structlagrange_1_1polyddg_1_1_hodge_decomposition_result" ],
        [ "PrincipalCurvaturesOptions", "structlagrange_1_1polyddg_1_1_principal_curvatures_options.html", "structlagrange_1_1polyddg_1_1_principal_curvatures_options" ],
        [ "PrincipalCurvaturesResult", "structlagrange_1_1polyddg_1_1_principal_curvatures_result.html", "structlagrange_1_1polyddg_1_1_principal_curvatures_result" ],
        [ "SmoothDirectionFieldOptions", "structlagrange_1_1polyddg_1_1_smooth_direction_field_options.html", "structlagrange_1_1polyddg_1_1_smooth_direction_field_options" ]
      ] ],
      [ "polyscope", null, [
        [ "PolyscopeTrait", "structlagrange_1_1polyscope_1_1_polyscope_trait.html", null ]
      ] ],
      [ "primitive", null, [
        [ "legacy", null, [
          [ "CircularArcSweepPath", "classlagrange_1_1primitive_1_1legacy_1_1_circular_arc_sweep_path.html", "classlagrange_1_1primitive_1_1legacy_1_1_circular_arc_sweep_path" ],
          [ "LinearSweepPath", "classlagrange_1_1primitive_1_1legacy_1_1_linear_sweep_path.html", "classlagrange_1_1primitive_1_1legacy_1_1_linear_sweep_path" ],
          [ "PolylineSweepPath", "classlagrange_1_1primitive_1_1legacy_1_1_polyline_sweep_path.html", "classlagrange_1_1primitive_1_1legacy_1_1_polyline_sweep_path" ],
          [ "RoundedConeConfig", "structlagrange_1_1primitive_1_1legacy_1_1_rounded_cone_config.html", "structlagrange_1_1primitive_1_1legacy_1_1_rounded_cone_config" ],
          [ "RoundedCubeConfig", "structlagrange_1_1primitive_1_1legacy_1_1_rounded_cube_config.html", "structlagrange_1_1primitive_1_1legacy_1_1_rounded_cube_config" ],
          [ "RoundedCylinderConfig", "structlagrange_1_1primitive_1_1legacy_1_1_rounded_cylinder_config.html", "structlagrange_1_1primitive_1_1legacy_1_1_rounded_cylinder_config" ],
          [ "RoundedPlaneConfig", "structlagrange_1_1primitive_1_1legacy_1_1_rounded_plane_config.html", "structlagrange_1_1primitive_1_1legacy_1_1_rounded_plane_config" ],
          [ "SphereConfig", "structlagrange_1_1primitive_1_1legacy_1_1_sphere_config.html", "structlagrange_1_1primitive_1_1legacy_1_1_sphere_config" ],
          [ "SweepPath", "classlagrange_1_1primitive_1_1legacy_1_1_sweep_path.html", "classlagrange_1_1primitive_1_1legacy_1_1_sweep_path" ],
          [ "TorusConfig", "structlagrange_1_1primitive_1_1legacy_1_1_torus_config.html", "structlagrange_1_1primitive_1_1legacy_1_1_torus_config" ]
        ] ],
        [ "DiscOptions", "structlagrange_1_1primitive_1_1_disc_options.html", "structlagrange_1_1primitive_1_1_disc_options" ],
        [ "IcosahedronOptions", "structlagrange_1_1primitive_1_1_icosahedron_options.html", "structlagrange_1_1primitive_1_1_icosahedron_options" ],
        [ "OctahedronOptions", "structlagrange_1_1primitive_1_1_octahedron_options.html", "structlagrange_1_1primitive_1_1_octahedron_options" ],
        [ "PrimitiveOptions", "structlagrange_1_1primitive_1_1_primitive_options.html", "structlagrange_1_1primitive_1_1_primitive_options" ],
        [ "RoundedConeOptions", "structlagrange_1_1primitive_1_1_rounded_cone_options.html", "structlagrange_1_1primitive_1_1_rounded_cone_options" ],
        [ "RoundedCubeOptions", "structlagrange_1_1primitive_1_1_rounded_cube_options.html", "structlagrange_1_1primitive_1_1_rounded_cube_options" ],
        [ "RoundedPlaneOptions", "structlagrange_1_1primitive_1_1_rounded_plane_options.html", "structlagrange_1_1primitive_1_1_rounded_plane_options" ],
        [ "SphereOptions", "structlagrange_1_1primitive_1_1_sphere_options.html", "structlagrange_1_1primitive_1_1_sphere_options" ],
        [ "SubdividedSphereOptions", "structlagrange_1_1primitive_1_1_subdivided_sphere_options.html", "structlagrange_1_1primitive_1_1_subdivided_sphere_options" ],
        [ "SweepOptions", "classlagrange_1_1primitive_1_1_sweep_options.html", "classlagrange_1_1primitive_1_1_sweep_options" ],
        [ "SweptSurfaceOptions", "structlagrange_1_1primitive_1_1_swept_surface_options.html", "structlagrange_1_1primitive_1_1_swept_surface_options" ],
        [ "TorusOptions", "structlagrange_1_1primitive_1_1_torus_options.html", "structlagrange_1_1primitive_1_1_torus_options" ]
      ] ],
      [ "python", null, [
        [ "GridWrapper", "structlagrange_1_1python_1_1_grid_wrapper.html", null ],
        [ "PyAttribute", "classlagrange_1_1python_1_1_py_attribute.html", null ],
        [ "PyIndexedAttribute", "classlagrange_1_1python_1_1_py_indexed_attribute.html", null ],
        [ "StubType", "structlagrange_1_1python_1_1_stub_type.html", null ]
      ] ],
      [ "raycasting", "namespacelagrange_1_1raycasting.html", [
        [ "detail", null, [
          [ "FacetInstanceData", "structlagrange_1_1raycasting_1_1detail_1_1_facet_instance_data.html", "structlagrange_1_1raycasting_1_1detail_1_1_facet_instance_data" ],
          [ "ImplBase", "structlagrange_1_1raycasting_1_1detail_1_1_impl_base.html", null ],
          [ "InstanceData", "structlagrange_1_1raycasting_1_1detail_1_1_instance_data.html", null ],
          [ "RayPacket16", "structlagrange_1_1raycasting_1_1detail_1_1_ray_packet16.html", "structlagrange_1_1raycasting_1_1detail_1_1_ray_packet16" ],
          [ "RaySampler", "structlagrange_1_1raycasting_1_1detail_1_1_ray_sampler.html", "structlagrange_1_1raycasting_1_1detail_1_1_ray_sampler" ]
        ] ],
        [ "internal", null, [
          [ "RayCasterOBBAccess", "structlagrange_1_1raycasting_1_1internal_1_1_ray_caster_o_b_b_access.html", null ]
        ] ],
        [ "legacy", null, [
          [ "ClosestPointResult", "structlagrange_1_1raycasting_1_1legacy_1_1_closest_point_result.html", null ],
          [ "EmbreeRayCaster", "classlagrange_1_1raycasting_1_1legacy_1_1_embree_ray_caster.html", "classlagrange_1_1raycasting_1_1legacy_1_1_embree_ray_caster" ],
          [ "RaycasterMesh", "classlagrange_1_1raycasting_1_1legacy_1_1_raycaster_mesh.html", null ],
          [ "RaycasterMeshDerived", "classlagrange_1_1raycasting_1_1legacy_1_1_raycaster_mesh_derived.html", null ]
        ] ],
        [ "ClosestPointHit", "structlagrange_1_1raycasting_1_1_closest_point_hit.html", "structlagrange_1_1raycasting_1_1_closest_point_hit" ],
        [ "ClosestPointHitN", "structlagrange_1_1raycasting_1_1_closest_point_hit_n.html", "structlagrange_1_1raycasting_1_1_closest_point_hit_n" ],
        [ "HitBase", "structlagrange_1_1raycasting_1_1_hit_base.html", "structlagrange_1_1raycasting_1_1_hit_base" ],
        [ "HitBaseN", "structlagrange_1_1raycasting_1_1_hit_base_n.html", "structlagrange_1_1raycasting_1_1_hit_base_n" ],
        [ "LocalFeatureSizeOptions", "structlagrange_1_1raycasting_1_1_local_feature_size_options.html", "structlagrange_1_1raycasting_1_1_local_feature_size_options" ],
        [ "OccludedFacetEstimateOptions", "structlagrange_1_1raycasting_1_1_occluded_facet_estimate_options.html", "structlagrange_1_1raycasting_1_1_occluded_facet_estimate_options" ],
        [ "OccludedFacetSampler", "classlagrange_1_1raycasting_1_1_occluded_facet_sampler.html", "classlagrange_1_1raycasting_1_1_occluded_facet_sampler" ],
        [ "OccludedFacetSamplerOptions", "structlagrange_1_1raycasting_1_1_occluded_facet_sampler_options.html", "structlagrange_1_1raycasting_1_1_occluded_facet_sampler_options" ],
        [ "OccludedInstanceEstimateOptions", "structlagrange_1_1raycasting_1_1_occluded_instance_estimate_options.html", "structlagrange_1_1raycasting_1_1_occluded_instance_estimate_options" ],
        [ "OccludedInstanceSampler", "classlagrange_1_1raycasting_1_1_occluded_instance_sampler.html", "classlagrange_1_1raycasting_1_1_occluded_instance_sampler" ],
        [ "ProjectCommonOptions", "structlagrange_1_1raycasting_1_1_project_common_options.html", "structlagrange_1_1raycasting_1_1_project_common_options" ],
        [ "ProjectDirectionalOptions", "structlagrange_1_1raycasting_1_1_project_directional_options.html", "structlagrange_1_1raycasting_1_1_project_directional_options" ],
        [ "ProjectOptions", "structlagrange_1_1raycasting_1_1_project_options.html", "structlagrange_1_1raycasting_1_1_project_options" ],
        [ "RayCaster", "classlagrange_1_1raycasting_1_1_ray_caster.html", "classlagrange_1_1raycasting_1_1_ray_caster" ],
        [ "RayHit", "structlagrange_1_1raycasting_1_1_ray_hit.html", "structlagrange_1_1raycasting_1_1_ray_hit" ],
        [ "RayHitN", "structlagrange_1_1raycasting_1_1_ray_hit_n.html", "structlagrange_1_1raycasting_1_1_ray_hit_n" ],
        [ "RemoveOccludedFacetsOptions", "structlagrange_1_1raycasting_1_1_remove_occluded_facets_options.html", "structlagrange_1_1raycasting_1_1_remove_occluded_facets_options" ]
      ] ],
      [ "remeshing_im", null, [
        [ "RemeshingOptions", "structlagrange_1_1remeshing__im_1_1_remeshing_options.html", "structlagrange_1_1remeshing__im_1_1_remeshing_options" ]
      ] ],
      [ "scene", null, [
        [ "detail", null, [
          [ "type_identity", "structlagrange_1_1scene_1_1detail_1_1type__identity.html", null ]
        ] ],
        [ "internal", null, [
          [ "SingleMeshToSceneOptions", "structlagrange_1_1scene_1_1internal_1_1_single_mesh_to_scene_options.html", null ]
        ] ],
        [ "Animation", "structlagrange_1_1scene_1_1_animation.html", null ],
        [ "Camera", "structlagrange_1_1scene_1_1_camera.html", null ],
        [ "Extensions", "structlagrange_1_1scene_1_1_extensions.html", "structlagrange_1_1scene_1_1_extensions" ],
        [ "ImageBufferExperimental", "structlagrange_1_1scene_1_1_image_buffer_experimental.html", "structlagrange_1_1scene_1_1_image_buffer_experimental" ],
        [ "ImageExperimental", "structlagrange_1_1scene_1_1_image_experimental.html", "structlagrange_1_1scene_1_1_image_experimental" ],
        [ "Light", "structlagrange_1_1scene_1_1_light.html", null ],
        [ "MaterialExperimental", "structlagrange_1_1scene_1_1_material_experimental.html", null ],
        [ "MeshesAndMaterialsResult", "structlagrange_1_1scene_1_1_meshes_and_materials_result.html", "structlagrange_1_1scene_1_1_meshes_and_materials_result" ],
        [ "MeshInstance", "structlagrange_1_1scene_1_1_mesh_instance.html", "structlagrange_1_1scene_1_1_mesh_instance" ],
        [ "Node", "structlagrange_1_1scene_1_1_node.html", null ],
        [ "RemeshingOptions", "structlagrange_1_1scene_1_1_remeshing_options.html", "structlagrange_1_1scene_1_1_remeshing_options" ],
        [ "Scene", "structlagrange_1_1scene_1_1_scene.html", "structlagrange_1_1scene_1_1_scene" ],
        [ "SceneMeshInstance", "structlagrange_1_1scene_1_1_scene_mesh_instance.html", null ],
        [ "SimpleScene", "classlagrange_1_1scene_1_1_simple_scene.html", "classlagrange_1_1scene_1_1_simple_scene" ],
        [ "Skeleton", "structlagrange_1_1scene_1_1_skeleton.html", null ],
        [ "Texture", "structlagrange_1_1scene_1_1_texture.html", null ],
        [ "TextureInfo", "structlagrange_1_1scene_1_1_texture_info.html", "structlagrange_1_1scene_1_1_texture_info" ],
        [ "UserDataConverter", "structlagrange_1_1scene_1_1_user_data_converter.html", null ],
        [ "Value", "classlagrange_1_1scene_1_1_value.html", null ]
      ] ],
      [ "serialization", null, [
        [ "internal", null, [
          [ "CistaAnimation", "structlagrange_1_1serialization_1_1internal_1_1_cista_animation.html", null ],
          [ "CistaAttributeInfo", "structlagrange_1_1serialization_1_1internal_1_1_cista_attribute_info.html", null ],
          [ "CistaCamera", "structlagrange_1_1serialization_1_1internal_1_1_cista_camera.html", null ],
          [ "CistaExtensions", "structlagrange_1_1serialization_1_1internal_1_1_cista_extensions.html", null ],
          [ "CistaImage", "structlagrange_1_1serialization_1_1internal_1_1_cista_image.html", null ],
          [ "CistaImageBuffer", "structlagrange_1_1serialization_1_1internal_1_1_cista_image_buffer.html", null ],
          [ "CistaInstance", "structlagrange_1_1serialization_1_1internal_1_1_cista_instance.html", "structlagrange_1_1serialization_1_1internal_1_1_cista_instance" ],
          [ "CistaLight", "structlagrange_1_1serialization_1_1internal_1_1_cista_light.html", null ],
          [ "CistaMaterial", "structlagrange_1_1serialization_1_1internal_1_1_cista_material.html", null ],
          [ "CistaMesh", "structlagrange_1_1serialization_1_1internal_1_1_cista_mesh.html", null ],
          [ "CistaNode", "structlagrange_1_1serialization_1_1internal_1_1_cista_node.html", null ],
          [ "CistaScene", "structlagrange_1_1serialization_1_1internal_1_1_cista_scene.html", null ],
          [ "CistaSceneMeshInstance", "structlagrange_1_1serialization_1_1internal_1_1_cista_scene_mesh_instance.html", null ],
          [ "CistaSimpleScene", "structlagrange_1_1serialization_1_1internal_1_1_cista_simple_scene.html", "structlagrange_1_1serialization_1_1internal_1_1_cista_simple_scene" ],
          [ "CistaSkeleton", "structlagrange_1_1serialization_1_1internal_1_1_cista_skeleton.html", null ],
          [ "CistaTexture", "structlagrange_1_1serialization_1_1internal_1_1_cista_texture.html", null ],
          [ "CistaTextureInfo", "structlagrange_1_1serialization_1_1internal_1_1_cista_texture_info.html", null ],
          [ "CistaValue", "structlagrange_1_1serialization_1_1internal_1_1_cista_value.html", null ]
        ] ],
        [ "DeserializeOptions", "structlagrange_1_1serialization_1_1_deserialize_options.html", "structlagrange_1_1serialization_1_1_deserialize_options" ],
        [ "SerializeOptions", "structlagrange_1_1serialization_1_1_serialize_options.html", "structlagrange_1_1serialization_1_1_serialize_options" ]
      ] ],
      [ "solver", null, [
        [ "EigenResult", "structlagrange_1_1solver_1_1_eigen_result.html", "structlagrange_1_1solver_1_1_eigen_result" ]
      ] ],
      [ "subdivision", "namespacelagrange_1_1subdivision.html", [
        [ "internal", null, [
          [ "OSDUV", "structlagrange_1_1subdivision_1_1internal_1_1_o_s_d_u_v.html", null ],
          [ "OSDVertex", "structlagrange_1_1subdivision_1_1internal_1_1_o_s_d_vertex.html", null ]
        ] ],
        [ "InterpolatedAttributeIds", "structlagrange_1_1subdivision_1_1_interpolated_attribute_ids.html", null ],
        [ "InterpolatedAttributes", "classlagrange_1_1subdivision_1_1_interpolated_attributes.html", "classlagrange_1_1subdivision_1_1_interpolated_attributes" ],
        [ "MeshConverter", "structlagrange_1_1subdivision_1_1_mesh_converter.html", null ],
        [ "SharpnessOptions", "structlagrange_1_1subdivision_1_1_sharpness_options.html", "structlagrange_1_1subdivision_1_1_sharpness_options" ],
        [ "SharpnessResults", "structlagrange_1_1subdivision_1_1_sharpness_results.html", "structlagrange_1_1subdivision_1_1_sharpness_results" ],
        [ "SubdivisionOptions", "structlagrange_1_1subdivision_1_1_subdivision_options.html", "structlagrange_1_1subdivision_1_1_subdivision_options" ]
      ] ],
      [ "testing", null, [
        [ "CreateOptions", "structlagrange_1_1testing_1_1_create_options.html", "structlagrange_1_1testing_1_1_create_options" ]
      ] ],
      [ "texproc", null, [
        [ "mesh_utils", null, [
          [ "MeshWrapper", "structlagrange_1_1texproc_1_1mesh__utils_1_1_mesh_wrapper.html", null ]
        ] ],
        [ "threadpool", null, [
          [ "ThreadPool", "structlagrange_1_1texproc_1_1threadpool_1_1_thread_pool.html", null ]
        ] ],
        [ "CompositingOptions", "structlagrange_1_1texproc_1_1_compositing_options.html", "structlagrange_1_1texproc_1_1_compositing_options" ],
        [ "ConstWeightedTextureView", "structlagrange_1_1texproc_1_1_const_weighted_texture_view.html", "structlagrange_1_1texproc_1_1_const_weighted_texture_view" ],
        [ "DilationOptions", "structlagrange_1_1texproc_1_1_dilation_options.html", "structlagrange_1_1texproc_1_1_dilation_options" ],
        [ "ExtractMeshWithAlphaMaskOptions", "structlagrange_1_1texproc_1_1_extract_mesh_with_alpha_mask_options.html", "structlagrange_1_1texproc_1_1_extract_mesh_with_alpha_mask_options" ],
        [ "FilteringOptions", "structlagrange_1_1texproc_1_1_filtering_options.html", "structlagrange_1_1texproc_1_1_filtering_options" ],
        [ "Padding", "classlagrange_1_1texproc_1_1_padding.html", null ],
        [ "StitchingOptions", "structlagrange_1_1texproc_1_1_stitching_options.html", "structlagrange_1_1texproc_1_1_stitching_options" ],
        [ "TextureRasterizer", "classlagrange_1_1texproc_1_1_texture_rasterizer.html", "classlagrange_1_1texproc_1_1_texture_rasterizer" ],
        [ "TextureRasterizerOptions", "structlagrange_1_1texproc_1_1_texture_rasterizer_options.html", "structlagrange_1_1texproc_1_1_texture_rasterizer_options" ]
      ] ],
      [ "ui", "namespacelagrange_1_1ui.html", [
        [ "detail", null, [
          [ "args_to_tuple", "structlagrange_1_1ui_1_1detail_1_1args__to__tuple.html", null ],
          [ "convert_implicit", "structlagrange_1_1ui_1_1detail_1_1convert__implicit.html", null ]
        ] ],
        [ "util", null, [
          [ "lambda_helper", "structlagrange_1_1ui_1_1util_1_1lambda__helper.html", null ],
          [ "lambda_helper< Result(F::*)(Args...) const >", "structlagrange_1_1ui_1_1util_1_1lambda__helper_3_01_result_07_f_1_1_5_08_07_args_8_8_8_08_01const_01_4.html", null ]
        ] ],
        [ "utils", null, [
          [ "pair_hash", "structlagrange_1_1ui_1_1utils_1_1pair__hash.html", null ],
          [ "value_field", "structlagrange_1_1ui_1_1utils_1_1value__field.html", null ],
          [ "value_field< double >", "structlagrange_1_1ui_1_1utils_1_1value__field_3_01double_01_4.html", null ],
          [ "value_field< float >", "structlagrange_1_1ui_1_1utils_1_1value__field_3_01float_01_4.html", null ],
          [ "value_field< int >", "structlagrange_1_1ui_1_1utils_1_1value__field_3_01int_01_4.html", null ]
        ] ],
        [ "AABB", "classlagrange_1_1ui_1_1_a_a_b_b.html", "classlagrange_1_1ui_1_1_a_a_b_b" ],
        [ "AcceleratedPicking", "structlagrange_1_1ui_1_1_accelerated_picking.html", null ],
        [ "AttributeRender", "structlagrange_1_1ui_1_1_attribute_render.html", "structlagrange_1_1ui_1_1_attribute_render" ],
        [ "Bounds", "structlagrange_1_1ui_1_1_bounds.html", "structlagrange_1_1ui_1_1_bounds" ],
        [ "Camera", "classlagrange_1_1ui_1_1_camera.html", "classlagrange_1_1ui_1_1_camera" ],
        [ "CameraChangedEvent", "structlagrange_1_1ui_1_1_camera_changed_event.html", null ],
        [ "CameraController", "structlagrange_1_1ui_1_1_camera_controller.html", null ],
        [ "CameraFocusAndFit", "structlagrange_1_1ui_1_1_camera_focus_and_fit.html", null ],
        [ "CameraTurntable", "structlagrange_1_1ui_1_1_camera_turntable.html", null ],
        [ "Color", "classlagrange_1_1ui_1_1_color.html", "classlagrange_1_1ui_1_1_color" ],
        [ "ColormapShaderMode", "structlagrange_1_1ui_1_1_colormap_shader_mode.html", null ],
        [ "ComponentPanel", "structlagrange_1_1ui_1_1_component_panel.html", null ],
        [ "DefaultLayers", "structlagrange_1_1ui_1_1_default_layers.html", null ],
        [ "DefaultPanels", "structlagrange_1_1ui_1_1_default_panels.html", null ],
        [ "DefaultShaderAtrribNames", "structlagrange_1_1ui_1_1_default_shader_atrrib_names.html", null ],
        [ "DefaultShaderIndicesNames", "structlagrange_1_1ui_1_1_default_shader_indices_names.html", null ],
        [ "DefaultShaders", "structlagrange_1_1ui_1_1_default_shaders.html", null ],
        [ "DefaultSystems", "structlagrange_1_1ui_1_1_default_systems.html", null ],
        [ "DefaultTools", "structlagrange_1_1ui_1_1_default_tools.html", null ],
        [ "DehoveredEvent", "structlagrange_1_1ui_1_1_dehovered_event.html", null ],
        [ "DeselectedEvent", "structlagrange_1_1ui_1_1_deselected_event.html", null ],
        [ "Dockspace", "structlagrange_1_1ui_1_1_dockspace.html", null ],
        [ "ElementEdge", "structlagrange_1_1ui_1_1_element_edge.html", null ],
        [ "ElementFace", "structlagrange_1_1ui_1_1_element_face.html", null ],
        [ "ElementObject", "structlagrange_1_1ui_1_1_element_object.html", null ],
        [ "ElementVertex", "structlagrange_1_1ui_1_1_element_vertex.html", null ],
        [ "EventEmitter", "structlagrange_1_1ui_1_1_event_emitter.html", null ],
        [ "FileDialogPath", "classlagrange_1_1ui_1_1_file_dialog_path.html", "classlagrange_1_1ui_1_1_file_dialog_path" ],
        [ "FileFilter", "structlagrange_1_1ui_1_1_file_filter.html", "structlagrange_1_1ui_1_1_file_filter" ],
        [ "FocusedViewportPanel", "structlagrange_1_1ui_1_1_focused_viewport_panel.html", null ],
        [ "FrameBuffer", "classlagrange_1_1ui_1_1_frame_buffer.html", null ],
        [ "Frustum", "classlagrange_1_1ui_1_1_frustum.html", null ],
        [ "GizmoContext", "structlagrange_1_1ui_1_1_gizmo_context.html", null ],
        [ "GizmoObjectTransform", "structlagrange_1_1ui_1_1_gizmo_object_transform.html", "structlagrange_1_1ui_1_1_gizmo_object_transform" ],
        [ "GLMesh", "structlagrange_1_1ui_1_1_g_l_mesh.html", null ],
        [ "GlobalTime", "structlagrange_1_1ui_1_1_global_time.html", "structlagrange_1_1ui_1_1_global_time" ],
        [ "GLQuery", "structlagrange_1_1ui_1_1_g_l_query.html", null ],
        [ "GLRenderQueueItem", "structlagrange_1_1ui_1_1_g_l_render_queue_item.html", null ],
        [ "GLScope", "structlagrange_1_1ui_1_1_g_l_scope.html", null ],
        [ "GLState", "structlagrange_1_1ui_1_1_g_l_state.html", null ],
        [ "GPUBuffer", "structlagrange_1_1ui_1_1_g_p_u_buffer.html", null ],
        [ "Hovered", "structlagrange_1_1ui_1_1_hovered.html", null ],
        [ "HoveredEvent", "structlagrange_1_1ui_1_1_hovered_event.html", null ],
        [ "HoveredTemp", "structlagrange_1_1ui_1_1_hovered_temp.html", null ],
        [ "IBL", "structlagrange_1_1ui_1_1_i_b_l.html", "structlagrange_1_1ui_1_1_i_b_l" ],
        [ "IBLChangedEvent", "structlagrange_1_1ui_1_1_i_b_l_changed_event.html", null ],
        [ "ImmediateEntities", "structlagrange_1_1ui_1_1_immediate_entities.html", null ],
        [ "InputState", "structlagrange_1_1ui_1_1_input_state.html", "structlagrange_1_1ui_1_1_input_state" ],
        [ "Keybinds", "classlagrange_1_1ui_1_1_keybinds.html", "classlagrange_1_1ui_1_1_keybinds" ],
        [ "LastTool", "structlagrange_1_1ui_1_1_last_tool.html", null ],
        [ "Layer", "structlagrange_1_1ui_1_1_layer.html", null ],
        [ "LightComponent", "structlagrange_1_1ui_1_1_light_component.html", null ],
        [ "LightComponentChangedEvent", "structlagrange_1_1ui_1_1_light_component_changed_event.html", null ],
        [ "LogData", "classlagrange_1_1ui_1_1_log_data.html", null ],
        [ "LoggerContextData", "structlagrange_1_1ui_1_1_logger_context_data.html", null ],
        [ "LoggerPanel", "structlagrange_1_1ui_1_1_logger_panel.html", null ],
        [ "MainMenuHeight", "structlagrange_1_1ui_1_1_main_menu_height.html", null ],
        [ "Material", "classlagrange_1_1ui_1_1_material.html", null ],
        [ "MeshData", "structlagrange_1_1ui_1_1_mesh_data.html", null ],
        [ "MeshDataDirty", "structlagrange_1_1ui_1_1_mesh_data_dirty.html", null ],
        [ "MeshElementIDMaterial", "structlagrange_1_1ui_1_1_mesh_element_i_d_material.html", null ],
        [ "MeshGeometry", "structlagrange_1_1ui_1_1_mesh_geometry.html", null ],
        [ "MeshRender", "structlagrange_1_1ui_1_1_mesh_render.html", null ],
        [ "MeshRenderChangedEvent", "structlagrange_1_1ui_1_1_mesh_render_changed_event.html", null ],
        [ "MeshSelectionRender", "structlagrange_1_1ui_1_1_mesh_selection_render.html", null ],
        [ "Name", "structlagrange_1_1ui_1_1_name.html", null ],
        [ "ObjectIDViewport", "structlagrange_1_1ui_1_1_object_i_d_viewport.html", null ],
        [ "PaginatedMatrixWidget", "classlagrange_1_1ui_1_1_paginated_matrix_widget.html", null ],
        [ "PayloadComponent", "structlagrange_1_1ui_1_1_payload_component.html", null ],
        [ "PayloadEntity", "structlagrange_1_1ui_1_1_payload_entity.html", null ],
        [ "PBRMaterial", "structlagrange_1_1ui_1_1_p_b_r_material.html", null ],
        [ "PostProcessQuadVertexData", "structlagrange_1_1ui_1_1_post_process_quad_vertex_data.html", null ],
        [ "RasterizerOptions", "structlagrange_1_1ui_1_1_rasterizer_options.html", null ],
        [ "RayFacetHit", "structlagrange_1_1ui_1_1_ray_facet_hit.html", null ],
        [ "RenderContext", "structlagrange_1_1ui_1_1_render_context.html", null ],
        [ "RotateToolTag", "structlagrange_1_1ui_1_1_rotate_tool_tag.html", null ],
        [ "ScaleToolTag", "structlagrange_1_1ui_1_1_scale_tool_tag.html", null ],
        [ "ScenePanel", "structlagrange_1_1ui_1_1_scene_panel.html", null ],
        [ "Selected", "structlagrange_1_1ui_1_1_selected.html", null ],
        [ "SelectedEvent", "structlagrange_1_1ui_1_1_selected_event.html", null ],
        [ "SelectionContext", "structlagrange_1_1ui_1_1_selection_context.html", "structlagrange_1_1ui_1_1_selection_context" ],
        [ "SelectionViewport", "structlagrange_1_1ui_1_1_selection_viewport.html", null ],
        [ "SelectToolTag", "structlagrange_1_1ui_1_1_select_tool_tag.html", null ],
        [ "Shader", "classlagrange_1_1ui_1_1_shader.html", null ],
        [ "ShaderBoolProperty", "structlagrange_1_1ui_1_1_shader_bool_property.html", null ],
        [ "ShaderColorProperty", "structlagrange_1_1ui_1_1_shader_color_property.html", null ],
        [ "ShaderDefinition", "structlagrange_1_1ui_1_1_shader_definition.html", null ],
        [ "ShaderException", "classlagrange_1_1ui_1_1_shader_exception.html", null ],
        [ "ShaderFloatProperty", "structlagrange_1_1ui_1_1_shader_float_property.html", null ],
        [ "ShaderIntProperty", "structlagrange_1_1ui_1_1_shader_int_property.html", null ],
        [ "ShaderLoader", "structlagrange_1_1ui_1_1_shader_loader.html", null ],
        [ "ShaderProperty", "structlagrange_1_1ui_1_1_shader_property.html", null ],
        [ "ShaderTextureProperty", "structlagrange_1_1ui_1_1_shader_texture_property.html", "structlagrange_1_1ui_1_1_shader_texture_property" ],
        [ "ShaderTextureValue", "structlagrange_1_1ui_1_1_shader_texture_value.html", null ],
        [ "ShaderValue", "structlagrange_1_1ui_1_1_shader_value.html", null ],
        [ "ShaderVectorProperty", "structlagrange_1_1ui_1_1_shader_vector_property.html", null ],
        [ "ShadowMap", "structlagrange_1_1ui_1_1_shadow_map.html", null ],
        [ "ShadowMapFBO", "structlagrange_1_1ui_1_1_shadow_map_f_b_o.html", null ],
        [ "ShadowmappingViewport", "structlagrange_1_1ui_1_1_shadowmapping_viewport.html", null ],
        [ "SkyboxCubeVertexData", "structlagrange_1_1ui_1_1_skybox_cube_vertex_data.html", null ],
        [ "SubSelection", "structlagrange_1_1ui_1_1_sub_selection.html", null ],
        [ "Systems", "classlagrange_1_1ui_1_1_systems.html", "classlagrange_1_1ui_1_1_systems" ],
        [ "TemporaryLigthVisualization", "structlagrange_1_1ui_1_1_temporary_ligth_visualization.html", null ],
        [ "Texture", "classlagrange_1_1ui_1_1_texture.html", "classlagrange_1_1ui_1_1_texture" ],
        [ "ToolbarPanel", "structlagrange_1_1ui_1_1_toolbar_panel.html", null ],
        [ "Tools", "classlagrange_1_1ui_1_1_tools.html", null ],
        [ "Transform", "structlagrange_1_1ui_1_1_transform.html", "structlagrange_1_1ui_1_1_transform" ],
        [ "TransformChangedEvent", "structlagrange_1_1ui_1_1_transform_changed_event.html", null ],
        [ "TranslateToolTag", "structlagrange_1_1ui_1_1_translate_tool_tag.html", null ],
        [ "TreeNode", "structlagrange_1_1ui_1_1_tree_node.html", null ],
        [ "type_traits", "structlagrange_1_1ui_1_1type__traits.html", null ],
        [ "type_traits< double >", "structlagrange_1_1ui_1_1type__traits_3_01double_01_4.html", null ],
        [ "type_traits< float >", "structlagrange_1_1ui_1_1type__traits_3_01float_01_4.html", null ],
        [ "type_traits< int16_t >", "structlagrange_1_1ui_1_1type__traits_3_01int16__t_01_4.html", null ],
        [ "type_traits< int32_t >", "structlagrange_1_1ui_1_1type__traits_3_01int32__t_01_4.html", null ],
        [ "type_traits< int8_t >", "structlagrange_1_1ui_1_1type__traits_3_01int8__t_01_4.html", null ],
        [ "type_traits< uint16_t >", "structlagrange_1_1ui_1_1type__traits_3_01uint16__t_01_4.html", null ],
        [ "type_traits< uint32_t >", "structlagrange_1_1ui_1_1type__traits_3_01uint32__t_01_4.html", null ],
        [ "type_traits< uint8_t >", "structlagrange_1_1ui_1_1type__traits_3_01uint8__t_01_4.html", null ],
        [ "TypeData", "structlagrange_1_1ui_1_1_type_data.html", null ],
        [ "UIPanel", "structlagrange_1_1ui_1_1_u_i_panel.html", "structlagrange_1_1ui_1_1_u_i_panel" ],
        [ "UIWidget", "classlagrange_1_1ui_1_1_u_i_widget.html", "classlagrange_1_1ui_1_1_u_i_widget" ],
        [ "VAO", "structlagrange_1_1ui_1_1_v_a_o.html", null ],
        [ "VertexBuffer", "structlagrange_1_1ui_1_1_vertex_buffer.html", "structlagrange_1_1ui_1_1_vertex_buffer" ],
        [ "VertexData", "structlagrange_1_1ui_1_1_vertex_data.html", null ],
        [ "Viewer", "classlagrange_1_1ui_1_1_viewer.html", "classlagrange_1_1ui_1_1_viewer" ],
        [ "ViewportComponent", "structlagrange_1_1ui_1_1_viewport_component.html", null ],
        [ "ViewportPanel", "structlagrange_1_1ui_1_1_viewport_panel.html", "structlagrange_1_1ui_1_1_viewport_panel" ],
        [ "WindowCloseEvent", "structlagrange_1_1ui_1_1_window_close_event.html", null ],
        [ "WindowDropEvent", "structlagrange_1_1ui_1_1_window_drop_event.html", null ],
        [ "WindowResizeEvent", "structlagrange_1_1ui_1_1_window_resize_event.html", null ],
        [ "WindowSize", "structlagrange_1_1ui_1_1_window_size.html", null ]
      ] ],
      [ "volume", null, [
        [ "legacy", null, [
          [ "MeshAdapter", "classlagrange_1_1volume_1_1legacy_1_1_mesh_adapter.html", "classlagrange_1_1volume_1_1legacy_1_1_mesh_adapter" ]
        ] ],
        [ "MeshToVolumeOptions", "structlagrange_1_1volume_1_1_mesh_to_volume_options.html", "structlagrange_1_1volume_1_1_mesh_to_volume_options" ],
        [ "NormalsFromVolumeOptions", "structlagrange_1_1volume_1_1_normals_from_volume_options.html", "structlagrange_1_1volume_1_1_normals_from_volume_options" ],
        [ "VolumeToMeshOptions", "structlagrange_1_1volume_1_1_volume_to_mesh_options.html", "structlagrange_1_1volume_1_1_volume_to_mesh_options" ]
      ] ],
      [ "winding", null, [
        [ "FastWindingNumber", "classlagrange_1_1winding_1_1_fast_winding_number.html", "classlagrange_1_1winding_1_1_fast_winding_number" ]
      ] ],
      [ "xatlas", null, [
        [ "internal", null, [
          [ "MeshAdapter", "structlagrange_1_1xatlas_1_1internal_1_1_mesh_adapter.html", "structlagrange_1_1xatlas_1_1internal_1_1_mesh_adapter" ],
          [ "ProgressBridge", "classlagrange_1_1xatlas_1_1internal_1_1_progress_bridge.html", "classlagrange_1_1xatlas_1_1internal_1_1_progress_bridge" ],
          [ "UvMeshAdapter", "structlagrange_1_1xatlas_1_1internal_1_1_uv_mesh_adapter.html", "structlagrange_1_1xatlas_1_1internal_1_1_uv_mesh_adapter" ]
        ] ],
        [ "AtlasEngine", "classlagrange_1_1xatlas_1_1_atlas_engine.html", "classlagrange_1_1xatlas_1_1_atlas_engine" ],
        [ "ChartOptions", "structlagrange_1_1xatlas_1_1_chart_options.html", "structlagrange_1_1xatlas_1_1_chart_options" ],
        [ "PackOptions", "structlagrange_1_1xatlas_1_1_pack_options.html", "structlagrange_1_1xatlas_1_1_pack_options" ],
        [ "RepackOptions", "structlagrange_1_1xatlas_1_1_repack_options.html", "structlagrange_1_1xatlas_1_1_repack_options" ],
        [ "SceneOptions", "structlagrange_1_1xatlas_1_1_scene_options.html", "structlagrange_1_1xatlas_1_1_scene_options" ],
        [ "UnwrapOptions", "structlagrange_1_1xatlas_1_1_unwrap_options.html", "structlagrange_1_1xatlas_1_1_unwrap_options" ]
      ] ],
      [ "ActingMeshGeometry", "classlagrange_1_1_acting_mesh_geometry.html", null ],
      [ "AdjacencyList", "classlagrange_1_1_adjacency_list.html", "classlagrange_1_1_adjacency_list" ],
      [ "Attribute", "classlagrange_1_1_attribute.html", "classlagrange_1_1_attribute" ],
      [ "AttributeBase", "classlagrange_1_1_attribute_base.html", "classlagrange_1_1_attribute_base" ],
      [ "AttributeFilter", "structlagrange_1_1_attribute_filter.html", "structlagrange_1_1_attribute_filter" ],
      [ "AttributeMatcher", "structlagrange_1_1_attribute_matcher.html", "structlagrange_1_1_attribute_matcher" ],
      [ "AttributeName", "structlagrange_1_1_attribute_name.html", null ],
      [ "Attributes", "classlagrange_1_1_attributes.html", null ],
      [ "BadCastError", "structlagrange_1_1_bad_cast_error.html", null ],
      [ "BitField", "classlagrange_1_1_bit_field.html", "classlagrange_1_1_bit_field" ],
      [ "CameraTransforms", "structlagrange_1_1_camera_transforms.html", "structlagrange_1_1_camera_transforms" ],
      [ "ChainEdgesOptions", "structlagrange_1_1_chain_edges_options.html", "structlagrange_1_1_chain_edges_options" ],
      [ "ChainEdgesResult", "structlagrange_1_1_chain_edges_result.html", "structlagrange_1_1_chain_edges_result" ],
      [ "CloseSmallHolesOptions", "structlagrange_1_1_close_small_holes_options.html", "structlagrange_1_1_close_small_holes_options" ],
      [ "ComponentOptions", "structlagrange_1_1_component_options.html", "structlagrange_1_1_component_options" ],
      [ "ComputePointcloudPCAOptions", "structlagrange_1_1_compute_pointcloud_p_c_a_options.html", "structlagrange_1_1_compute_pointcloud_p_c_a_options" ],
      [ "Connectivity", "classlagrange_1_1_connectivity.html", null ],
      [ "copy_on_write_ptr", "classlagrange_1_1copy__on__write__ptr.html", "classlagrange_1_1copy__on__write__ptr" ],
      [ "CornerNormalOptions", "structlagrange_1_1_corner_normal_options.html", "structlagrange_1_1_corner_normal_options" ],
      [ "DihedralAngleOptions", "structlagrange_1_1_dihedral_angle_options.html", "structlagrange_1_1_dihedral_angle_options" ],
      [ "DijkstraDistanceOptions", "structlagrange_1_1_dijkstra_distance_options.html", "structlagrange_1_1_dijkstra_distance_options" ],
      [ "DisconnectUVChartsOptions", "structlagrange_1_1_disconnect_u_v_charts_options.html", "structlagrange_1_1_disconnect_u_v_charts_options" ],
      [ "DisjointSets", "classlagrange_1_1_disjoint_sets.html", "classlagrange_1_1_disjoint_sets" ],
      [ "DisjointSetsWithSize", "classlagrange_1_1_disjoint_sets_with_size.html", null ],
      [ "EdgeLengthOptions", "structlagrange_1_1_edge_length_options.html", "structlagrange_1_1_edge_length_options" ],
      [ "EdgeManifoldOptions", "structlagrange_1_1_edge_manifold_options.html", "structlagrange_1_1_edge_manifold_options" ],
      [ "EdgeType", "classlagrange_1_1_edge_type.html", "classlagrange_1_1_edge_type" ],
      [ "Error", "structlagrange_1_1_error.html", null ],
      [ "ExactPredicates", "classlagrange_1_1_exact_predicates.html", "classlagrange_1_1_exact_predicates" ],
      [ "ExactPredicatesShewchuk", "classlagrange_1_1_exact_predicates_shewchuk.html", "classlagrange_1_1_exact_predicates_shewchuk" ],
      [ "FacetAreaOptions", "structlagrange_1_1_facet_area_options.html", "structlagrange_1_1_facet_area_options" ],
      [ "FacetCentroidOptions", "structlagrange_1_1_facet_centroid_options.html", "structlagrange_1_1_facet_centroid_options" ],
      [ "FacetCircumcenterOptions", "structlagrange_1_1_facet_circumcenter_options.html", "structlagrange_1_1_facet_circumcenter_options" ],
      [ "FacetNormalOptions", "structlagrange_1_1_facet_normal_options.html", "structlagrange_1_1_facet_normal_options" ],
      [ "FacetVectorAreaOptions", "structlagrange_1_1_facet_vector_area_options.html", "structlagrange_1_1_facet_vector_area_options" ],
      [ "Frustum", "structlagrange_1_1_frustum.html", "structlagrange_1_1_frustum" ],
      [ "FrustumSelectionOptions", "structlagrange_1_1_frustum_selection_options.html", "structlagrange_1_1_frustum_selection_options" ],
      [ "function_ref", "classlagrange_1_1function__ref.html", null ],
      [ "function_ref< R(Args...)>", "classlagrange_1_1function__ref_3_01_r_07_args_8_8_8_08_4.html", "classlagrange_1_1function__ref_3_01_r_07_args_8_8_8_08_4" ],
      [ "GenuineMeshGeometry", "classlagrange_1_1_genuine_mesh_geometry.html", null ],
      [ "GreedyColoringOptions", "structlagrange_1_1_greedy_coloring_options.html", "structlagrange_1_1_greedy_coloring_options" ],
      [ "IndexedAttribute", "classlagrange_1_1_indexed_attribute.html", "classlagrange_1_1_indexed_attribute" ],
      [ "IndexedAttributes", "classlagrange_1_1_indexed_attributes.html", null ],
      [ "IsolineOptions", "structlagrange_1_1_isoline_options.html", "structlagrange_1_1_isoline_options" ],
      [ "Mesh", "classlagrange_1_1_mesh.html", "classlagrange_1_1_mesh" ],
      [ "MeshAreaOptions", "structlagrange_1_1_mesh_area_options.html", "structlagrange_1_1_mesh_area_options" ],
      [ "MeshBase", "classlagrange_1_1_mesh_base.html", null ],
      [ "MeshCentroidOptions", "structlagrange_1_1_mesh_centroid_options.html", "structlagrange_1_1_mesh_centroid_options" ],
      [ "MeshCovarianceOptions", "structlagrange_1_1_mesh_covariance_options.html", "structlagrange_1_1_mesh_covariance_options" ],
      [ "MeshGeometry", "classlagrange_1_1_mesh_geometry.html", null ],
      [ "MeshNavigation", "classlagrange_1_1_mesh_navigation.html", "classlagrange_1_1_mesh_navigation" ],
      [ "MeshTrait", "structlagrange_1_1_mesh_trait.html", null ],
      [ "NormalOptions", "structlagrange_1_1_normal_options.html", "structlagrange_1_1_normal_options" ],
      [ "OrderedPairHash", "structlagrange_1_1_ordered_pair_hash.html", null ],
      [ "OrderedPairHash< std::pair< U, V > >", "structlagrange_1_1_ordered_pair_hash_3_01std_1_1pair_3_01_u_00_01_v_01_4_01_4.html", null ],
      [ "OrientationOptions", "structlagrange_1_1_orientation_options.html", "structlagrange_1_1_orientation_options" ],
      [ "OrientOptions", "structlagrange_1_1_orient_options.html", "structlagrange_1_1_orient_options" ],
      [ "ParsingError", "structlagrange_1_1_parsing_error.html", null ],
      [ "PointcloudPCAOutput", "structlagrange_1_1_pointcloud_p_c_a_output.html", "structlagrange_1_1_pointcloud_p_c_a_output" ],
      [ "ProgressCallback", "classlagrange_1_1_progress_callback.html", "classlagrange_1_1_progress_callback" ],
      [ "RemapVerticesOptions", "structlagrange_1_1_remap_vertices_options.html", "structlagrange_1_1_remap_vertices_options" ],
      [ "RemoveDuplicateFacetOptions", "structlagrange_1_1_remove_duplicate_facet_options.html", "structlagrange_1_1_remove_duplicate_facet_options" ],
      [ "RemoveDuplicateVerticesOptions", "structlagrange_1_1_remove_duplicate_vertices_options.html", "structlagrange_1_1_remove_duplicate_vertices_options" ],
      [ "RemoveNullAreaFacetsOptions", "structlagrange_1_1_remove_null_area_facets_options.html", "structlagrange_1_1_remove_null_area_facets_options" ],
      [ "RemoveShortEdgesOptions", "structlagrange_1_1_remove_short_edges_options.html", "structlagrange_1_1_remove_short_edges_options" ],
      [ "RescaleUVOptions", "structlagrange_1_1_rescale_u_v_options.html", "structlagrange_1_1_rescale_u_v_options" ],
      [ "SamplePointsOnSurfaceOutput", "structlagrange_1_1_sample_points_on_surface_output.html", null ],
      [ "ScopedLogLevel", "classlagrange_1_1_scoped_log_level.html", "classlagrange_1_1_scoped_log_level" ],
      [ "ScopedTimer", "classlagrange_1_1_scoped_timer.html", "classlagrange_1_1_scoped_timer" ],
      [ "SeamEdgesOptions", "structlagrange_1_1_seam_edges_options.html", "structlagrange_1_1_seam_edges_options" ],
      [ "SelectFacetsByNormalSimilarityOptions", "structlagrange_1_1_select_facets_by_normal_similarity_options.html", "structlagrange_1_1_select_facets_by_normal_similarity_options" ],
      [ "SeparateByComponentsOptions", "structlagrange_1_1_separate_by_components_options.html", "structlagrange_1_1_separate_by_components_options" ],
      [ "SeparateByFacetGroupsOptions", "structlagrange_1_1_separate_by_facet_groups_options.html", "structlagrange_1_1_separate_by_facet_groups_options" ],
      [ "SharedSpan", "classlagrange_1_1_shared_span.html", "classlagrange_1_1_shared_span" ],
      [ "SilentMultiTimer", "classlagrange_1_1_silent_multi_timer.html", "classlagrange_1_1_silent_multi_timer" ],
      [ "SilentTimer", "classlagrange_1_1_silent_timer.html", "classlagrange_1_1_silent_timer" ],
      [ "SmallVector", "classlagrange_1_1_small_vector.html", null ],
      [ "SplitLongEdgesOptions", "structlagrange_1_1_split_long_edges_options.html", "structlagrange_1_1_split_long_edges_options" ],
      [ "SplitObtuseTrianglesOptions", "structlagrange_1_1_split_obtuse_triangles_options.html", "structlagrange_1_1_split_obtuse_triangles_options" ],
      [ "StackSet", "structlagrange_1_1_stack_set.html", null ],
      [ "StackVector", "structlagrange_1_1_stack_vector.html", null ],
      [ "StaticAssertableBool", "structlagrange_1_1_static_assertable_bool.html", null ],
      [ "SubmeshOptions", "structlagrange_1_1_submesh_options.html", "structlagrange_1_1_submesh_options" ],
      [ "SurfaceMesh", "classlagrange_1_1_surface_mesh.html", "classlagrange_1_1_surface_mesh" ],
      [ "TangentBitangentOptions", "structlagrange_1_1_tangent_bitangent_options.html", "structlagrange_1_1_tangent_bitangent_options" ],
      [ "TangentBitangentResult", "structlagrange_1_1_tangent_bitangent_result.html", "structlagrange_1_1_tangent_bitangent_result" ],
      [ "ThickenAndCloseOptions", "structlagrange_1_1_thicken_and_close_options.html", "structlagrange_1_1_thicken_and_close_options" ],
      [ "TransformOptions", "structlagrange_1_1_transform_options.html", "structlagrange_1_1_transform_options" ],
      [ "TriangulationOptions", "structlagrange_1_1_triangulation_options.html", "structlagrange_1_1_triangulation_options" ],
      [ "UnflipUVChartsOptions", "structlagrange_1_1_unflip_u_v_charts_options.html", "structlagrange_1_1_unflip_u_v_charts_options" ],
      [ "UnflipUVOptions", "structlagrange_1_1_unflip_u_v_options.html", "structlagrange_1_1_unflip_u_v_options" ],
      [ "UniqueAttributeNameOptions", "structlagrange_1_1_unique_attribute_name_options.html", "structlagrange_1_1_unique_attribute_name_options" ],
      [ "UVChartOptions", "structlagrange_1_1_u_v_chart_options.html", "structlagrange_1_1_u_v_chart_options" ],
      [ "UVDistortionOptions", "structlagrange_1_1_u_v_distortion_options.html", "structlagrange_1_1_u_v_distortion_options" ],
      [ "UVMeshOptions", "structlagrange_1_1_u_v_mesh_options.html", "structlagrange_1_1_u_v_mesh_options" ],
      [ "UVOrientationCount", "structlagrange_1_1_u_v_orientation_count.html", "structlagrange_1_1_u_v_orientation_count" ],
      [ "UVOrientationOptions", "structlagrange_1_1_u_v_orientation_options.html", "structlagrange_1_1_u_v_orientation_options" ],
      [ "value_ptr", "classlagrange_1_1value__ptr.html", null ],
      [ "VerboseTimer", "classlagrange_1_1_verbose_timer.html", "classlagrange_1_1_verbose_timer" ],
      [ "VertexManifoldOptions", "structlagrange_1_1_vertex_manifold_options.html", "structlagrange_1_1_vertex_manifold_options" ],
      [ "VertexNormalOptions", "structlagrange_1_1_vertex_normal_options.html", "structlagrange_1_1_vertex_normal_options" ],
      [ "VertexValenceOptions", "structlagrange_1_1_vertex_valence_options.html", "structlagrange_1_1_vertex_valence_options" ],
      [ "WeldOptions", "structlagrange_1_1_weld_options.html", "structlagrange_1_1_weld_options" ]
    ] ],
    [ "nanobind", null, [
      [ "detail", null, [
        [ "type_caster< lagrange::python::StubType< T, Hint > >", "structnanobind_1_1detail_1_1type__caster_3_01lagrange_1_1python_1_1_stub_type_3_01_t_00_01_hint_01_4_01_4.html", null ]
      ] ]
    ] ],
    [ "std", null, [
      [ "hash< lagrange::EdgeType< Index > >", "structstd_1_1hash_3_01lagrange_1_1_edge_type_3_01_index_01_4_01_4.html", null ]
    ] ],
    [ "Args", "struct_args.html", null ],
    [ "DemoState", "struct_demo_state.html", "struct_demo_state" ],
    [ "OrientReturn", "struct_orient_return.html", null ],
    [ "PickedPoint", "struct_picked_point.html", null ],
    [ "type_caster< lagrange::scene::Value >", "structtype__caster_3_01lagrange_1_1scene_1_1_value_01_4.html", null ],
    [ "type_caster< lagrange::StackVector< T, N > >", "structtype__caster_3_01lagrange_1_1_stack_vector_3_01_t_00_01_n_01_4_01_4.html", null ],
    [ "UiState", "struct_ui_state.html", null ]
];