var hierarchy =
[
    [ "AABB< Scalar, Dim >", "classlagrange_1_1bvh_1_1_a_a_b_b.html", null ],
    [ "AcceleratedPicking", "structlagrange_1_1ui_1_1_accelerated_picking.html", null ],
    [ "AdjacencyList< Index >", "classlagrange_1_1_adjacency_list.html", null ],
    [ "AlignedBox3f", null, [
      [ "AABB", "classlagrange_1_1ui_1_1_a_a_b_b.html", null ]
    ] ],
    [ "Animation", "structlagrange_1_1scene_1_1_animation.html", null ],
    [ "Args", "struct_args.html", null ],
    [ "args_to_tuple< Args >", "structlagrange_1_1ui_1_1detail_1_1args__to__tuple.html", null ],
    [ "ArrayBase", "classlagrange_1_1experimental_1_1_array_base.html", [
      [ "EigenArray< EigenType >", "classlagrange_1_1experimental_1_1_eigen_array.html", null ],
      [ "EigenArray< _EigenType >", "classlagrange_1_1experimental_1_1_eigen_array.html", null ]
    ] ],
    [ "ArraySerialization< T >", "structlagrange_1_1experimental_1_1internal_1_1_array_serialization.html", null ],
    [ "ArrayTypeInfo< Data >", "classlagrange_1_1experimental_1_1_array_type_info.html", null ],
    [ "AsFunction< T >", "structlagrange_1_1ui_1_1util_1_1_as_function.html", null ],
    [ "AsFunction< ReturnType(*)(Arg)>", "structlagrange_1_1ui_1_1util_1_1_as_function_3_01_return_type_07_5_08_07_arg_08_4.html", null ],
    [ "AsFunction< ReturnType(Arg) const >", "structlagrange_1_1ui_1_1util_1_1_as_function_3_01_return_type_07_arg_08_01const_01_4.html", null ],
    [ "AsFunction< ReturnType(Class::*)(Arg) const >", "structlagrange_1_1ui_1_1util_1_1_as_function_3_01_return_type_07_class_1_1_5_08_07_arg_08_01const_01_4.html", null ],
    [ "Attribute", "classlagrange_1_1experimental_1_1_attribute.html", null ],
    [ "AttributeBase", "classlagrange_1_1_attribute_base.html", [
      [ "Attribute< ValueType >", "classlagrange_1_1_attribute.html", null ],
      [ "Attribute< Index >", "classlagrange_1_1_attribute.html", null ],
      [ "Attribute< ValueType_ >", "classlagrange_1_1_attribute.html", null ],
      [ "IndexedAttribute< ValueType_, Index_ >", "classlagrange_1_1_indexed_attribute.html", null ]
    ] ],
    [ "AttributeEvaluator", "classlagrange_1_1poisson_1_1_attribute_evaluator.html", null ],
    [ "AttributeFilter", "structlagrange_1_1_attribute_filter.html", null ],
    [ "AttributeManager", "classlagrange_1_1experimental_1_1_attribute_manager.html", null ],
    [ "AttributeMatcher", "structlagrange_1_1_attribute_matcher.html", null ],
    [ "AttributeName", "structlagrange_1_1_attribute_name.html", null ],
    [ "AttributeRender", "structlagrange_1_1ui_1_1_attribute_render.html", null ],
    [ "Attributes< _AttributeArray >", "classlagrange_1_1_attributes.html", null ],
    [ "AttributeSmoothingOptions", "structlagrange_1_1filtering_1_1_attribute_smoothing_options.html", null ],
    [ "BareMeshTag", "structlagrange_1_1_surface_mesh_1_1_bare_mesh_tag.html", null ],
    [ "base_sink", null, [
      [ "PythonLoggingSink", "classlagrange_1_1python_1_1_python_logging_sink.html", null ]
    ] ],
    [ "BitField< EnumType_ >", "classlagrange_1_1_bit_field.html", null ],
    [ "bitset", null, [
      [ "Layer", "structlagrange_1_1ui_1_1_layer.html", null ]
    ] ],
    [ "Bounds", "structlagrange_1_1ui_1_1_bounds.html", null ],
    [ "BucketSortOffset< Index >", "structlagrange_1_1internal_1_1_bucket_sort_offset.html", null ],
    [ "BucketSortResult< Index >", "structlagrange_1_1internal_1_1_bucket_sort_result.html", null ],
    [ "BVH< _VertexArray, _ElementArray >", "classlagrange_1_1bvh_1_1_b_v_h.html", null ],
    [ "BVH< _VertexArray, lagrange::Triangles >", "classlagrange_1_1bvh_1_1_b_v_h.html", [
      [ "AABBIGL< _VertexArray, _ElementArray >", "classlagrange_1_1bvh_1_1_a_a_b_b_i_g_l.html", null ],
      [ "BVHNanoflann< _VertexArray, _ElementArray >", "classlagrange_1_1bvh_1_1_b_v_h_nanoflann.html", null ]
    ] ],
    [ "Camera", "structlagrange_1_1scene_1_1_camera.html", null ],
    [ "Camera", "classlagrange_1_1ui_1_1_camera.html", null ],
    [ "CameraChangedEvent", "structlagrange_1_1ui_1_1_camera_changed_event.html", null ],
    [ "CameraController", "structlagrange_1_1ui_1_1_camera_controller.html", null ],
    [ "CameraFocusAndFit", "structlagrange_1_1ui_1_1_camera_focus_and_fit.html", null ],
    [ "CameraOptions", "structlagrange_1_1texproc_1_1_camera_options.html", null ],
    [ "CameraTurntable", "structlagrange_1_1ui_1_1_camera_turntable.html", null ],
    [ "ChainEdgesOptions", "structlagrange_1_1_chain_edges_options.html", null ],
    [ "ChainEdgesResult< Index >", "structlagrange_1_1_chain_edges_result.html", null ],
    [ "CloseSmallHolesOptions", "structlagrange_1_1_close_small_holes_options.html", null ],
    [ "ClosestPoint", "structlagrange_1_1bvh_1_1_b_v_h_1_1_closest_point.html", null ],
    [ "ClosestPointResult< Scalar >", "structlagrange_1_1raycasting_1_1_closest_point_result.html", null ],
    [ "ColormapShaderMode", "structlagrange_1_1ui_1_1_colormap_shader_mode.html", null ],
    [ "CommonOptions", "structlagrange_1_1poisson_1_1_common_options.html", [
      [ "EvaluatorOptions", "structlagrange_1_1poisson_1_1_evaluator_options.html", null ],
      [ "ReconstructionOptions", "structlagrange_1_1poisson_1_1_reconstruction_options.html", null ]
    ] ],
    [ "ComponentOptions", "structlagrange_1_1_component_options.html", null ],
    [ "ComponentPanel", "structlagrange_1_1ui_1_1_component_panel.html", null ],
    [ "Components< GeometryType >", "classlagrange_1_1legacy_1_1_components.html", null ],
    [ "CompositingOptions", "structlagrange_1_1texproc_1_1_compositing_options.html", null ],
    [ "ComputeBorderedComponentsOutput< Index >", "structlagrange_1_1legacy_1_1_compute_bordered_components_output.html", null ],
    [ "ComputeMeshCentroidOutput< Scalar >", "structlagrange_1_1legacy_1_1_compute_mesh_centroid_output.html", null ],
    [ "ComputePointcloudPCAOptions", "structlagrange_1_1_compute_pointcloud_p_c_a_options.html", null ],
    [ "ComputePointcloudPCAOutput< Scalar >", "structlagrange_1_1legacy_1_1_compute_pointcloud_p_c_a_output.html", null ],
    [ "Connectivity< GeometryType >", "classlagrange_1_1_connectivity.html", null ],
    [ "ConstWeightedTextureView< ValueType >", "structlagrange_1_1texproc_1_1_const_weighted_texture_view.html", null ],
    [ "control_block_base", "classlagrange_1_1internal_1_1control__block__base.html", [
      [ "control_block< T, D >", "classlagrange_1_1internal_1_1control__block.html", null ]
    ] ],
    [ "convert_image_pixel< PIX_SRC, PIX_DST >", "structlagrange_1_1image_1_1convert__image__pixel.html", null ],
    [ "convert_implicit< T >", "structlagrange_1_1ui_1_1detail_1_1convert__implicit.html", null ],
    [ "copy_on_write_ptr< T >", "classlagrange_1_1copy__on__write__ptr.html", null ],
    [ "CornerNormalOptions", "structlagrange_1_1_corner_normal_options.html", null ],
    [ "CreateOptions", "structlagrange_1_1testing_1_1_create_options.html", null ],
    [ "DataDescription", "structlagrange_1_1ui_1_1_vertex_buffer_1_1_data_description.html", null ],
    [ "default_delete< T >", "classlagrange_1_1internal_1_1default__delete.html", null ],
    [ "default_delete< T[]>", "classlagrange_1_1internal_1_1default__delete_3_01_t_0f_0e_4.html", null ],
    [ "DefaultLayers", "structlagrange_1_1ui_1_1_default_layers.html", null ],
    [ "DefaultPanels", "structlagrange_1_1ui_1_1_default_panels.html", null ],
    [ "DefaultShaderAtrribNames", "structlagrange_1_1ui_1_1_default_shader_atrrib_names.html", null ],
    [ "DefaultShaderIndicesNames", "structlagrange_1_1ui_1_1_default_shader_indices_names.html", null ],
    [ "DefaultShaders", "structlagrange_1_1ui_1_1_default_shaders.html", null ],
    [ "DefaultSystems", "structlagrange_1_1ui_1_1_default_systems.html", null ],
    [ "DefaultTools", "structlagrange_1_1ui_1_1_default_tools.html", null ],
    [ "DehoveredEvent", "structlagrange_1_1ui_1_1_dehovered_event.html", null ],
    [ "DeselectedEvent", "structlagrange_1_1ui_1_1_deselected_event.html", null ],
    [ "DifferentialOperators< Scalar, Index >", "classlagrange_1_1polyddg_1_1_differential_operators.html", null ],
    [ "DihedralAngleOptions", "structlagrange_1_1_dihedral_angle_options.html", null ],
    [ "DijkstraDistanceOptions< Scalar, Index >", "structlagrange_1_1_dijkstra_distance_options.html", null ],
    [ "DilationOptions", "structlagrange_1_1texproc_1_1_dilation_options.html", null ],
    [ "DisjointSets< IndexType >", "classlagrange_1_1_disjoint_sets.html", [
      [ "DisjointSetsWithSize< IndexType >", "classlagrange_1_1_disjoint_sets_with_size.html", null ]
    ] ],
    [ "Dockspace", "structlagrange_1_1ui_1_1_dockspace.html", null ],
    [ "DownloadResult", "structlagrange_1_1ui_1_1_texture_1_1_download_result.html", null ],
    [ "Earcut< N >", "classlagrange_1_1mapbox_1_1detail_1_1_earcut.html", null ],
    [ "EdgeAABBTree< VertexArray, EdgeArray, Dim >", "structlagrange_1_1bvh_1_1_edge_a_a_b_b_tree.html", null ],
    [ "EdgeLengthOptions", "structlagrange_1_1_edge_length_options.html", null ],
    [ "EdgeManifoldOptions", "structlagrange_1_1_edge_manifold_options.html", null ],
    [ "EdgeType< Index >", "classlagrange_1_1_edge_type.html", null ],
    [ "EigenArrayRef< _EigenType, IsConst >", "classlagrange_1_1experimental_1_1_eigen_array_ref.html", null ],
    [ "EigenResult< Scalar >", "structlagrange_1_1solver_1_1_eigen_result.html", null ],
    [ "ElementEdge", "structlagrange_1_1ui_1_1_element_edge.html", null ],
    [ "ElementFace", "structlagrange_1_1ui_1_1_element_face.html", null ],
    [ "ElementObject", "structlagrange_1_1ui_1_1_element_object.html", null ],
    [ "ElementVertex", "structlagrange_1_1ui_1_1_element_vertex.html", null ],
    [ "EmbreeRayCaster< ScalarType >", "classlagrange_1_1raycasting_1_1_embree_ray_caster.html", null ],
    [ "emitter", null, [
      [ "EventEmitter", "structlagrange_1_1ui_1_1_event_emitter.html", null ]
    ] ],
    [ "EnumToScalar< type >", "structlagrange_1_1experimental_1_1_enum_to_scalar.html", null ],
    [ "EnumToScalar< ScalarEnum::DOUBLE >", "structlagrange_1_1experimental_1_1_enum_to_scalar_3_01_scalar_enum_1_1_d_o_u_b_l_e_01_4.html", null ],
    [ "EnumToScalar< ScalarEnum::FLOAT >", "structlagrange_1_1experimental_1_1_enum_to_scalar_3_01_scalar_enum_1_1_f_l_o_a_t_01_4.html", null ],
    [ "EnumToScalar< ScalarEnum::INT16 >", "structlagrange_1_1experimental_1_1_enum_to_scalar_3_01_scalar_enum_1_1_i_n_t16_01_4.html", null ],
    [ "EnumToScalar< ScalarEnum::INT32 >", "structlagrange_1_1experimental_1_1_enum_to_scalar_3_01_scalar_enum_1_1_i_n_t32_01_4.html", null ],
    [ "EnumToScalar< ScalarEnum::INT64 >", "structlagrange_1_1experimental_1_1_enum_to_scalar_3_01_scalar_enum_1_1_i_n_t64_01_4.html", null ],
    [ "EnumToScalar< ScalarEnum::INT8 >", "structlagrange_1_1experimental_1_1_enum_to_scalar_3_01_scalar_enum_1_1_i_n_t8_01_4.html", null ],
    [ "EnumToScalar< ScalarEnum::UINT16 >", "structlagrange_1_1experimental_1_1_enum_to_scalar_3_01_scalar_enum_1_1_u_i_n_t16_01_4.html", null ],
    [ "EnumToScalar< ScalarEnum::UINT32 >", "structlagrange_1_1experimental_1_1_enum_to_scalar_3_01_scalar_enum_1_1_u_i_n_t32_01_4.html", null ],
    [ "EnumToScalar< ScalarEnum::UINT64 >", "structlagrange_1_1experimental_1_1_enum_to_scalar_3_01_scalar_enum_1_1_u_i_n_t64_01_4.html", null ],
    [ "EnumToScalar< ScalarEnum::UINT8 >", "structlagrange_1_1experimental_1_1_enum_to_scalar_3_01_scalar_enum_1_1_u_i_n_t8_01_4.html", null ],
    [ "ExactPredicates", "classlagrange_1_1_exact_predicates.html", [
      [ "ExactPredicatesShewchuk", "classlagrange_1_1_exact_predicates_shewchuk.html", null ]
    ] ],
    [ "Extensions", "structlagrange_1_1scene_1_1_extensions.html", null ],
    [ "FacetAreaOptions", "structlagrange_1_1_facet_area_options.html", null ],
    [ "FacetCentroidOptions", "structlagrange_1_1_facet_centroid_options.html", null ],
    [ "FacetCircumcenterOptions", "structlagrange_1_1_facet_circumcenter_options.html", null ],
    [ "FacetNormalOptions", "structlagrange_1_1_facet_normal_options.html", null ],
    [ "FacetVectorAreaOptions", "structlagrange_1_1_facet_vector_area_options.html", null ],
    [ "false_type", null, [
      [ "is_mesh_helper< T, void >", "structlagrange_1_1_mesh_trait_helper_1_1is__mesh__helper.html", null ],
      [ "is_mesh_helper< MeshType, typename Void< typename MeshType::VertexArray, typename MeshType::FacetArray >::type >", "structlagrange_1_1_mesh_trait_helper_1_1is__mesh__helper_3_01_mesh_type_00_01typename_01_void_3_189721d847f0585e54612704ceb864c0.html", null ],
      [ "is_mesh_smart_ptr_helper< T, void >", "structlagrange_1_1_mesh_trait_helper_1_1is__mesh__smart__ptr__helper.html", null ],
      [ "is_mesh_smart_ptr_helper< MeshTypePtr, typename Void< typename MeshTypePtr::element_type, typename MeshTypePtr::element_type::VertexArray, typename MeshTypePtr::element_type::FacetArray >::type >", "structlagrange_1_1_mesh_trait_helper_1_1is__mesh__smart__ptr__helper_3_01_mesh_type_ptr_00_01typdd3a1b441f06e428de34247e1df62704.html", null ],
      [ "is_range< Derived, std::enable_if_t< std::is_base_of< Eigen::DenseBase< Derived >, Derived >::value, char > >", "structfmt_1_1is__range_3_01_derived_00_01std_1_1enable__if__t_3_01std_1_1is__base__of_3_01_eigen8831e8e9466b492bd5196648eda925fb.html", null ],
      [ "is_mesh_helper< T, _ >", "structlagrange_1_1_mesh_trait_helper_1_1is__mesh__helper.html", null ],
      [ "is_mesh_smart_ptr_helper< T, _ >", "structlagrange_1_1_mesh_trait_helper_1_1is__mesh__smart__ptr__helper.html", null ]
    ] ],
    [ "FastWindingNumber", "classlagrange_1_1winding_1_1_fast_winding_number.html", null ],
    [ "FileDialogPath", "classlagrange_1_1ui_1_1_file_dialog_path.html", null ],
    [ "FileDialogPathImpl", "structlagrange_1_1ui_1_1_file_dialog_path_1_1_file_dialog_path_impl.html", null ],
    [ "FileFilter", "structlagrange_1_1ui_1_1_file_filter.html", null ],
    [ "FilteringOptions", "structlagrange_1_1texproc_1_1_filtering_options.html", null ],
    [ "FocusedViewportPanel", "structlagrange_1_1ui_1_1_focused_viewport_panel.html", null ],
    [ "FrameBuffer", "classlagrange_1_1ui_1_1_frame_buffer.html", null ],
    [ "Frustum< Scalar >", "structlagrange_1_1_frustum.html", null ],
    [ "Frustum", "classlagrange_1_1ui_1_1_frustum.html", null ],
    [ "FrustumSelectionOptions", "structlagrange_1_1_frustum_selection_options.html", null ],
    [ "function_ref< F >", "classlagrange_1_1function__ref.html", null ],
    [ "function_ref< R(Args...)>", "classlagrange_1_1function__ref_3_01_r_07_args_8_8_8_08_4.html", null ],
    [ "GeodesicEngine< Scalar, Index >", "classlagrange_1_1geodesic_1_1_geodesic_engine.html", [
      [ "Impl", "structlagrange_1_1geodesic_1_1_geodesic_engine_heat_1_1_impl.html", null ],
      [ "Impl", "structlagrange_1_1geodesic_1_1_geodesic_engine_m_m_p_1_1_impl.html", null ],
      [ "GeodesicEngineDGPC< Scalar, Index >", "classlagrange_1_1geodesic_1_1_geodesic_engine_d_g_p_c.html", null ],
      [ "GeodesicEngineHeat< Scalar, Index >", "classlagrange_1_1geodesic_1_1_geodesic_engine_heat.html", null ],
      [ "GeodesicEngineMMP< Scalar, Index >", "classlagrange_1_1geodesic_1_1_geodesic_engine_m_m_p.html", null ]
    ] ],
    [ "GeometricProfile< VertexArray, Index >", "structlagrange_1_1legacy_1_1_geometric_profile.html", null ],
    [ "GizmoContext", "structlagrange_1_1ui_1_1_gizmo_context.html", null ],
    [ "GizmoObjectTransform", "structlagrange_1_1ui_1_1_gizmo_object_transform.html", null ],
    [ "GLMesh", "structlagrange_1_1ui_1_1_g_l_mesh.html", null ],
    [ "GlobalTime", "structlagrange_1_1ui_1_1_global_time.html", null ],
    [ "GLQuery", "structlagrange_1_1ui_1_1_g_l_query.html", null ],
    [ "GLRenderQueueItem", "structlagrange_1_1ui_1_1_g_l_render_queue_item.html", null ],
    [ "GLScope", "structlagrange_1_1ui_1_1_g_l_scope.html", null ],
    [ "GLState", "structlagrange_1_1ui_1_1_g_l_state.html", null ],
    [ "GPUBuffer", "structlagrange_1_1ui_1_1_g_p_u_buffer.html", null ],
    [ "GreedyColoringOptions", "structlagrange_1_1_greedy_coloring_options.html", null ],
    [ "hash< lagrange::EdgeType< Index > >", "structstd_1_1hash_3_01lagrange_1_1_edge_type_3_01_index_01_4_01_4.html", null ],
    [ "Hovered", "structlagrange_1_1ui_1_1_hovered.html", null ],
    [ "HoveredEvent", "structlagrange_1_1ui_1_1_hovered_event.html", null ],
    [ "HoveredTemp", "structlagrange_1_1ui_1_1_hovered_temp.html", null ],
    [ "IBL", "structlagrange_1_1ui_1_1_i_b_l.html", null ],
    [ "IBLChangedEvent", "structlagrange_1_1ui_1_1_i_b_l_changed_event.html", null ],
    [ "ImageBufferExperimental", "structlagrange_1_1scene_1_1_image_buffer_experimental.html", null ],
    [ "ImageExperimental", "structlagrange_1_1scene_1_1_image_experimental.html", null ],
    [ "ImageHistogram", "structlagrange_1_1image_1_1_image_histogram.html", null ],
    [ "ImageStorage", "classlagrange_1_1image_1_1_image_storage.html", null ],
    [ "ImageTraits< TYPE >", "structlagrange_1_1image_1_1_image_traits.html", null ],
    [ "ImageViewBase", "classlagrange_1_1image_1_1_image_view_base.html", [
      [ "ImageView< T >", "classlagrange_1_1image_1_1_image_view.html", null ]
    ] ],
    [ "ImmediateEntities", "structlagrange_1_1ui_1_1_immediate_entities.html", null ],
    [ "Impl", "structlagrange_1_1poisson_1_1_attribute_evaluator_1_1_impl.html", [
      [ "Derived< ValueType >", "structlagrange_1_1poisson_1_1_attribute_evaluator_1_1_impl_1_1_derived.html", null ]
    ] ],
    [ "Impl", "structlagrange_1_1winding_1_1_fast_winding_number_1_1_impl.html", null ],
    [ "IndexedAttribute", "classlagrange_1_1experimental_1_1_indexed_attribute.html", null ],
    [ "IndexedAttributeManager", "classlagrange_1_1experimental_1_1_indexed_attribute_manager.html", null ],
    [ "IndexedAttributes< _AttributeArray, _IndexArray >", "classlagrange_1_1_indexed_attributes.html", null ],
    [ "InputState", "structlagrange_1_1ui_1_1_input_state.html", null ],
    [ "InterpolatedAttributeIds", "structlagrange_1_1subdivision_1_1_interpolated_attribute_ids.html", null ],
    [ "InterpolatedAttributes", "classlagrange_1_1subdivision_1_1_interpolated_attributes.html", null ],
    [ "InverseMapping< Index >", "structlagrange_1_1internal_1_1_inverse_mapping.html", null ],
    [ "IsolineOptions", "structlagrange_1_1_isoline_options.html", null ],
    [ "iterator", "classlagrange_1_1_edge_type_1_1iterator.html", null ],
    [ "Keybind", "structlagrange_1_1ui_1_1_keybinds_1_1_keybind.html", null ],
    [ "Keybinds", "classlagrange_1_1ui_1_1_keybinds.html", null ],
    [ "lambda_helper< F >", "structlagrange_1_1ui_1_1util_1_1lambda__helper.html", null ],
    [ "lambda_helper< Result(F::*)(Args...) const >", "structlagrange_1_1ui_1_1util_1_1lambda__helper_3_01_result_07_f_1_1_5_08_07_args_8_8_8_08_01const_01_4.html", null ],
    [ "LastTool", "structlagrange_1_1ui_1_1_last_tool.html", null ],
    [ "Light", "structlagrange_1_1scene_1_1_light.html", null ],
    [ "LightComponent", "structlagrange_1_1ui_1_1_light_component.html", null ],
    [ "LightComponentChangedEvent", "structlagrange_1_1ui_1_1_light_component_changed_event.html", null ],
    [ "list_caster", null, [
      [ "type_caster< lagrange::StackVector< T, N > >", "structtype__caster_3_01lagrange_1_1_stack_vector_3_01_t_00_01_n_01_4_01_4.html", null ]
    ] ],
    [ "LoadImageResult", "structlagrange_1_1image__io_1_1_load_image_result.html", null ],
    [ "LoadOptions", "structlagrange_1_1io_1_1_load_options.html", null ],
    [ "LogData", "classlagrange_1_1ui_1_1_log_data.html", null ],
    [ "LoggerContextData", "structlagrange_1_1ui_1_1_logger_context_data.html", null ],
    [ "LoggerPanel", "structlagrange_1_1ui_1_1_logger_panel.html", null ],
    [ "MainMenuHeight", "structlagrange_1_1ui_1_1_main_menu_height.html", null ],
    [ "MapAttributesOptions", "structlagrange_1_1internal_1_1_map_attributes_options.html", null ],
    [ "MarchingTrianglesOutput< MeshType_ >", "structlagrange_1_1legacy_1_1_marching_triangles_output.html", null ],
    [ "Material", "classlagrange_1_1ui_1_1_material.html", null ],
    [ "MaterialExperimental", "structlagrange_1_1scene_1_1_material_experimental.html", null ],
    [ "MeshAdapter< MeshType >", "classlagrange_1_1volume_1_1legacy_1_1_mesh_adapter.html", null ],
    [ "MeshAreaOptions", "structlagrange_1_1_mesh_area_options.html", null ],
    [ "MeshBase", "classlagrange_1_1_mesh_base.html", [
      [ "Mesh< Vertices3D, Triangles >", "classlagrange_1_1_mesh.html", null ],
      [ "Mesh< Vertices2D, Triangles >", "classlagrange_1_1_mesh.html", null ],
      [ "Mesh< Vertices3Df, Triangles >", "classlagrange_1_1_mesh.html", null ],
      [ "Mesh< Vertices2Df, Triangles >", "classlagrange_1_1_mesh.html", null ],
      [ "Mesh< Vertices3D, Quads >", "classlagrange_1_1_mesh.html", null ],
      [ "Mesh< Vertices2D, Quads >", "classlagrange_1_1_mesh.html", null ],
      [ "Mesh< Vertices3Df, Quads >", "classlagrange_1_1_mesh.html", null ],
      [ "Mesh< Vertices2Df, Quads >", "classlagrange_1_1_mesh.html", null ],
      [ "Mesh< VertexArray, FacetArray >", "classlagrange_1_1_mesh.html", null ],
      [ "Mesh< AttributeArray, IndexArray >", "classlagrange_1_1_mesh.html", null ],
      [ "Mesh< _VertexArray, _FacetArray >", "classlagrange_1_1_mesh.html", null ]
    ] ],
    [ "MeshCentroidOptions", "structlagrange_1_1_mesh_centroid_options.html", null ],
    [ "MeshConverter< SurfaceMeshT >", "structlagrange_1_1subdivision_1_1_mesh_converter.html", null ],
    [ "MeshCovarianceOptions", "structlagrange_1_1_mesh_covariance_options.html", null ],
    [ "MeshData", "structlagrange_1_1ui_1_1_mesh_data.html", null ],
    [ "MeshDataDirty", "structlagrange_1_1ui_1_1_mesh_data_dirty.html", null ],
    [ "MeshElementIDMaterial", "structlagrange_1_1ui_1_1_mesh_element_i_d_material.html", null ],
    [ "MeshGeometry< _VertexArray, _FacetArray >", "classlagrange_1_1_mesh_geometry.html", [
      [ "GenuineMeshGeometry< AttributeArray, IndexArray >", "classlagrange_1_1_genuine_mesh_geometry.html", null ],
      [ "ActingMeshGeometry< _VertexArray, _FacetArray >", "classlagrange_1_1_acting_mesh_geometry.html", null ],
      [ "GenuineMeshGeometry< _VertexArray, _FacetArray >", "classlagrange_1_1_genuine_mesh_geometry.html", null ]
    ] ],
    [ "MeshGeometry", "structlagrange_1_1ui_1_1_mesh_geometry.html", null ],
    [ "MeshInstance< Scalar, Index, Dimension >", "structlagrange_1_1scene_1_1_mesh_instance.html", null ],
    [ "MeshLoaderParams", "structlagrange_1_1io_1_1legacy_1_1_mesh_loader_params.html", null ],
    [ "MeshLoaderResult< MeshType >", "structlagrange_1_1io_1_1legacy_1_1_mesh_loader_result.html", null ],
    [ "MeshMapping< MeshType >", "structlagrange_1_1legacy_1_1_mesh_mapping.html", [
      [ "BackwardMeshMapping< MeshType >", "structlagrange_1_1legacy_1_1_backward_mesh_mapping.html", null ],
      [ "ForwardMeshMapping< MeshType >", "structlagrange_1_1legacy_1_1_forward_mesh_mapping.html", null ]
    ] ],
    [ "MeshNavigation< MeshType >", "classlagrange_1_1_mesh_navigation.html", null ],
    [ "MeshRender", "structlagrange_1_1ui_1_1_mesh_render.html", null ],
    [ "MeshRenderChangedEvent", "structlagrange_1_1ui_1_1_mesh_render_changed_event.html", null ],
    [ "MeshSelectionRender", "structlagrange_1_1ui_1_1_mesh_selection_render.html", null ],
    [ "MeshTopology< MeshType >", "classlagrange_1_1legacy_1_1_mesh_topology.html", null ],
    [ "MeshToVolumeOptions", "structlagrange_1_1volume_1_1_mesh_to_volume_options.html", null ],
    [ "MeshTrait< MeshType_ >", "structlagrange_1_1_mesh_trait.html", null ],
    [ "MeshWrapper< Scalar, Index >", "structlagrange_1_1texproc_1_1mesh__utils_1_1_mesh_wrapper.html", null ],
    [ "Mouse", "structlagrange_1_1ui_1_1_input_state_1_1_mouse.html", null ],
    [ "Name", "structlagrange_1_1ui_1_1_name.html", null ],
    [ "nested_formatter", null, [
      [ "formatter< T, std::enable_if_t< std::is_base_of< Eigen::DenseBase< T >, T >::value, char > >", "structfmt_1_1formatter_3_01_t_00_01std_1_1enable__if__t_3_01std_1_1is__base__of_3_01_eigen_1_1_d4cad164886cc373111d40252deee7ffc.html", null ]
    ] ],
    [ "Node", "structlagrange_1_1scene_1_1_node.html", null ],
    [ "NormalOptions", "structlagrange_1_1_normal_options.html", null ],
    [ "NormalsFromVolumeOptions", "structlagrange_1_1volume_1_1_normals_from_volume_options.html", null ],
    [ "nth< I, T >", "structlagrange_1_1mapbox_1_1util_1_1nth.html", null ],
    [ "ObjectIDViewport", "structlagrange_1_1ui_1_1_object_i_d_viewport.html", null ],
    [ "ObjReaderResult< Scalar, Index >", "structlagrange_1_1io_1_1internal_1_1_obj_reader_result.html", null ],
    [ "OrderedPairHash< T, Enable >", "structlagrange_1_1_ordered_pair_hash.html", null ],
    [ "OrderedPairHash< std::pair< U, V > >", "structlagrange_1_1_ordered_pair_hash_3_01std_1_1pair_3_01_u_00_01_v_01_4_01_4.html", null ],
    [ "OrientationOptions", "structlagrange_1_1_orientation_options.html", null ],
    [ "OrientOptions", "structlagrange_1_1_orient_options.html", null ],
    [ "OSDUV< MeshType >", "structlagrange_1_1subdivision_1_1internal_1_1_o_s_d_u_v.html", null ],
    [ "OSDVertex< MeshType >", "structlagrange_1_1subdivision_1_1internal_1_1_o_s_d_vertex.html", null ],
    [ "PackingOptions", "structlagrange_1_1packing_1_1legacy_1_1_packing_options.html", null ],
    [ "Padding", "classlagrange_1_1texproc_1_1_padding.html", null ],
    [ "PaginatedMatrixWidget", "classlagrange_1_1ui_1_1_paginated_matrix_widget.html", null ],
    [ "pair_hash", "structlagrange_1_1ui_1_1utils_1_1pair__hash.html", null ],
    [ "Params", "structlagrange_1_1ui_1_1_texture_1_1_params.html", null ],
    [ "PayloadComponent", "structlagrange_1_1ui_1_1_payload_component.html", null ],
    [ "PayloadEntity", "structlagrange_1_1ui_1_1_payload_entity.html", null ],
    [ "PBRMaterial", "structlagrange_1_1ui_1_1_p_b_r_material.html", null ],
    [ "PixelTraits< Scalar, NumChannels >", "structlagrange_1_1image_1_1_raw_input_image_1_1_pixel_traits.html", null ],
    [ "PixelTraits< Scalar, 1 >", "structlagrange_1_1image_1_1_raw_input_image_1_1_pixel_traits_3_01_scalar_00_011_01_4.html", null ],
    [ "Plane", "structlagrange_1_1_frustum_1_1_plane.html", null ],
    [ "PointcloudPCAOutput< Scalar >", "structlagrange_1_1_pointcloud_p_c_a_output.html", null ],
    [ "PointToPointGeodesicOptions", "structlagrange_1_1geodesic_1_1_point_to_point_geodesic_options.html", null ],
    [ "PolyscopeTrait< PolyscopeStructure >", "structlagrange_1_1polyscope_1_1_polyscope_trait.html", null ],
    [ "PostProcessQuadVertexData", "structlagrange_1_1ui_1_1_post_process_quad_vertex_data.html", null ],
    [ "PrimitiveOptions", "structlagrange_1_1primitive_1_1_primitive_options.html", [
      [ "DiscOptions", "structlagrange_1_1primitive_1_1_disc_options.html", null ],
      [ "IcosahedronOptions", "structlagrange_1_1primitive_1_1_icosahedron_options.html", null ],
      [ "OctahedronOptions", "structlagrange_1_1primitive_1_1_octahedron_options.html", null ],
      [ "RoundedConeOptions", "structlagrange_1_1primitive_1_1_rounded_cone_options.html", null ],
      [ "RoundedCubeOptions", "structlagrange_1_1primitive_1_1_rounded_cube_options.html", null ],
      [ "RoundedPlaneOptions", "structlagrange_1_1primitive_1_1_rounded_plane_options.html", null ],
      [ "SphereOptions", "structlagrange_1_1primitive_1_1_sphere_options.html", null ],
      [ "SubdividedSphereOptions", "structlagrange_1_1primitive_1_1_subdivided_sphere_options.html", null ],
      [ "SweptSurfaceOptions", "structlagrange_1_1primitive_1_1_swept_surface_options.html", null ],
      [ "TorusOptions", "structlagrange_1_1primitive_1_1_torus_options.html", null ]
    ] ],
    [ "ProgressCallback", "classlagrange_1_1_progress_callback.html", null ],
    [ "ptr< T, D >", "classlagrange_1_1internal_1_1ptr.html", null ],
    [ "PyAttribute", "classlagrange_1_1python_1_1_py_attribute.html", null ],
    [ "PyEdgeAABBTree< Scalar, Index, Dim >", "classlagrange_1_1bvh_1_1_py_edge_a_a_b_b_tree.html", null ],
    [ "PyIndexedAttribute", "classlagrange_1_1python_1_1_py_indexed_attribute.html", null ],
    [ "RasterizerOptions", "structlagrange_1_1ui_1_1_rasterizer_options.html", null ],
    [ "RawArray< _Scalar, _Rows, _Cols, _Options, IsConst >", "classlagrange_1_1experimental_1_1_raw_array.html", null ],
    [ "RawInputImage", "classlagrange_1_1image_1_1_raw_input_image.html", null ],
    [ "Ray", "structlagrange_1_1ui_1_1_camera_1_1_ray.html", null ],
    [ "RaycasterMesh", "classlagrange_1_1raycasting_1_1_raycaster_mesh.html", [
      [ "RaycasterMeshDerived< MeshType >", "classlagrange_1_1raycasting_1_1_raycaster_mesh_derived.html", null ]
    ] ],
    [ "RayFacetHit", "structlagrange_1_1ui_1_1_ray_facet_hit.html", null ],
    [ "RemapVerticesOptions", "structlagrange_1_1_remap_vertices_options.html", null ],
    [ "RemeshingOptions", "structlagrange_1_1scene_1_1_remeshing_options.html", null ],
    [ "RemoveDuplicateFacetOptions", "structlagrange_1_1_remove_duplicate_facet_options.html", null ],
    [ "RemoveDuplicateVerticesOptions", "structlagrange_1_1_remove_duplicate_vertices_options.html", null ],
    [ "RemoveNullAreaFacetsOptions", "structlagrange_1_1_remove_null_area_facets_options.html", null ],
    [ "RenderContext", "structlagrange_1_1ui_1_1_render_context.html", null ],
    [ "RepackOptions", "structlagrange_1_1packing_1_1_repack_options.html", null ],
    [ "RescaleUVOptions", "structlagrange_1_1_rescale_u_v_options.html", null ],
    [ "ReservedAttributeIds", "structlagrange_1_1_surface_mesh_1_1_reserved_attribute_ids.html", null ],
    [ "RotateToolTag", "structlagrange_1_1ui_1_1_rotate_tool_tag.html", null ],
    [ "RoundedConeConfig", "structlagrange_1_1primitive_1_1legacy_1_1_rounded_cone_config.html", null ],
    [ "RoundedCubeConfig", "structlagrange_1_1primitive_1_1legacy_1_1_rounded_cube_config.html", null ],
    [ "RoundedCylinderConfig", "structlagrange_1_1primitive_1_1legacy_1_1_rounded_cylinder_config.html", null ],
    [ "RoundedPlaneConfig", "structlagrange_1_1primitive_1_1legacy_1_1_rounded_plane_config.html", null ],
    [ "runtime_error", null, [
      [ "Error", "structlagrange_1_1_error.html", [
        [ "BadCastError", "structlagrange_1_1_bad_cast_error.html", null ],
        [ "ParsingError", "structlagrange_1_1_parsing_error.html", null ]
      ] ],
      [ "PackingFailure", "classlagrange_1_1packing_1_1_packing_failure.html", null ],
      [ "PackingFailure", "classlagrange_1_1packing_1_1legacy_1_1_packing_failure.html", null ],
      [ "ShaderException", "classlagrange_1_1ui_1_1_shader_exception.html", null ]
    ] ],
    [ "SamplePointsOnSurfaceOutput< MeshType >", "structlagrange_1_1_sample_points_on_surface_output.html", null ],
    [ "SaveOptions", "structlagrange_1_1io_1_1_save_options.html", null ],
    [ "ScalarToEnum< T, T2 >", "structlagrange_1_1experimental_1_1_scalar_to_enum.html", null ],
    [ "ScalarToEnum< double, void >", "structlagrange_1_1experimental_1_1_scalar_to_enum_3_01double_00_01void_01_4.html", null ],
    [ "ScalarToEnum< float, void >", "structlagrange_1_1experimental_1_1_scalar_to_enum_3_01float_00_01void_01_4.html", null ],
    [ "ScalarToEnum< int16_t, void >", "structlagrange_1_1experimental_1_1_scalar_to_enum_3_01int16__t_00_01void_01_4.html", null ],
    [ "ScalarToEnum< int32_t, void >", "structlagrange_1_1experimental_1_1_scalar_to_enum_3_01int32__t_00_01void_01_4.html", null ],
    [ "ScalarToEnum< int64_t, void >", "structlagrange_1_1experimental_1_1_scalar_to_enum_3_01int64__t_00_01void_01_4.html", null ],
    [ "ScalarToEnum< int8_t, void >", "structlagrange_1_1experimental_1_1_scalar_to_enum_3_01int8__t_00_01void_01_4.html", null ],
    [ "ScalarToEnum< uint16_t, void >", "structlagrange_1_1experimental_1_1_scalar_to_enum_3_01uint16__t_00_01void_01_4.html", null ],
    [ "ScalarToEnum< uint32_t, void >", "structlagrange_1_1experimental_1_1_scalar_to_enum_3_01uint32__t_00_01void_01_4.html", null ],
    [ "ScalarToEnum< uint64_t, void >", "structlagrange_1_1experimental_1_1_scalar_to_enum_3_01uint64__t_00_01void_01_4.html", null ],
    [ "ScalarToEnum< uint8_t, void >", "structlagrange_1_1experimental_1_1_scalar_to_enum_3_01uint8__t_00_01void_01_4.html", null ],
    [ "ScaleToolTag", "structlagrange_1_1ui_1_1_scale_tool_tag.html", null ],
    [ "Scene< Scalar, Index >", "structlagrange_1_1scene_1_1_scene.html", null ],
    [ "SceneMeshInstance", "structlagrange_1_1scene_1_1_scene_mesh_instance.html", null ],
    [ "ScenePanel", "structlagrange_1_1ui_1_1_scene_panel.html", null ],
    [ "ScopedLogLevel", "classlagrange_1_1_scoped_log_level.html", null ],
    [ "ScopedTimer", "classlagrange_1_1_scoped_timer.html", null ],
    [ "SeamEdgesOptions", "structlagrange_1_1_seam_edges_options.html", null ],
    [ "Selected", "structlagrange_1_1ui_1_1_selected.html", null ],
    [ "SelectedEvent", "structlagrange_1_1ui_1_1_selected_event.html", null ],
    [ "SelectFacetsByNormalSimilarityOptions", "structlagrange_1_1_select_facets_by_normal_similarity_options.html", null ],
    [ "SelectFacetsByNormalSimilarityParameters< MeshType >", "structlagrange_1_1legacy_1_1_select_facets_by_normal_similarity_parameters.html", null ],
    [ "SelectionContext", "structlagrange_1_1ui_1_1_selection_context.html", null ],
    [ "SelectionViewport", "structlagrange_1_1ui_1_1_selection_viewport.html", null ],
    [ "SelectToolTag", "structlagrange_1_1ui_1_1_select_tool_tag.html", null ],
    [ "SeparateByComponentsOptions", "structlagrange_1_1_separate_by_components_options.html", null ],
    [ "SeparateByFacetGroupsOptions", "structlagrange_1_1_separate_by_facet_groups_options.html", null ],
    [ "Shader", "classlagrange_1_1ui_1_1_shader.html", null ],
    [ "ShaderDefinition", "structlagrange_1_1ui_1_1_shader_definition.html", null ],
    [ "ShaderLoader", "structlagrange_1_1ui_1_1_shader_loader.html", null ],
    [ "ShaderProperty< T >", "structlagrange_1_1ui_1_1_shader_property.html", null ],
    [ "ShaderProperty< bool >", "structlagrange_1_1ui_1_1_shader_property.html", [
      [ "ShaderBoolProperty", "structlagrange_1_1ui_1_1_shader_bool_property.html", null ]
    ] ],
    [ "ShaderProperty< Color >", "structlagrange_1_1ui_1_1_shader_property.html", [
      [ "ShaderColorProperty", "structlagrange_1_1ui_1_1_shader_color_property.html", null ]
    ] ],
    [ "ShaderProperty< Eigen::Vector4f >", "structlagrange_1_1ui_1_1_shader_property.html", [
      [ "ShaderVectorProperty", "structlagrange_1_1ui_1_1_shader_vector_property.html", null ]
    ] ],
    [ "ShaderProperty< float >", "structlagrange_1_1ui_1_1_shader_property.html", [
      [ "ShaderFloatProperty", "structlagrange_1_1ui_1_1_shader_float_property.html", null ]
    ] ],
    [ "ShaderProperty< int >", "structlagrange_1_1ui_1_1_shader_property.html", [
      [ "ShaderIntProperty", "structlagrange_1_1ui_1_1_shader_int_property.html", null ]
    ] ],
    [ "ShaderProperty< ShaderTextureValue >", "structlagrange_1_1ui_1_1_shader_property.html", [
      [ "ShaderTextureProperty", "structlagrange_1_1ui_1_1_shader_texture_property.html", null ]
    ] ],
    [ "ShaderTextureValue", "structlagrange_1_1ui_1_1_shader_texture_value.html", null ],
    [ "ShaderValue", "structlagrange_1_1ui_1_1_shader_value.html", null ],
    [ "ShadowMap", "structlagrange_1_1ui_1_1_shadow_map.html", null ],
    [ "ShadowMapFBO", "structlagrange_1_1ui_1_1_shadow_map_f_b_o.html", null ],
    [ "shared_ptr_access< T, bool, bool >", "classlagrange_1_1internal_1_1shared__ptr__access.html", [
      [ "shared_ptr< T >", "classlagrange_1_1internal_1_1shared__ptr.html", null ]
    ] ],
    [ "shared_ptr_access< T, false, true >", "classlagrange_1_1internal_1_1shared__ptr__access_3_01_t_00_01false_00_01true_01_4.html", null ],
    [ "shared_ptr_access< T, true, false >", "classlagrange_1_1internal_1_1shared__ptr__access_3_01_t_00_01true_00_01false_01_4.html", null ],
    [ "SharedSpan< T >", "classlagrange_1_1_shared_span.html", null ],
    [ "SilentMultiTimer", "classlagrange_1_1_silent_multi_timer.html", null ],
    [ "SilentTimer", "classlagrange_1_1_silent_timer.html", null ],
    [ "SimpleScene< Scalar, Index, Dimension >", "classlagrange_1_1scene_1_1_simple_scene.html", null ],
    [ "SingleSourceGeodesicOptions", "structlagrange_1_1geodesic_1_1_single_source_geodesic_options.html", null ],
    [ "SingleSourceGeodesicResult", "structlagrange_1_1geodesic_1_1_single_source_geodesic_result.html", null ],
    [ "Skeleton", "structlagrange_1_1scene_1_1_skeleton.html", null ],
    [ "SkinningExtractNResult< Scalar, Index >", "structlagrange_1_1internal_1_1_skinning_extract_n_result.html", null ],
    [ "SkyboxCubeVertexData", "structlagrange_1_1ui_1_1_skybox_cube_vertex_data.html", null ],
    [ "SmoothingOptions", "structlagrange_1_1filtering_1_1_smoothing_options.html", null ],
    [ "SolverOptions", "structlagrange_1_1texproc_1_1_compositing_options_1_1_solver_options.html", null ],
    [ "SphereConfig", "structlagrange_1_1primitive_1_1legacy_1_1_sphere_config.html", null ],
    [ "SplitLongEdgesOptions", "structlagrange_1_1_split_long_edges_options.html", null ],
    [ "StackSet< T, N >", "structlagrange_1_1_stack_set.html", null ],
    [ "StackVector< T, N >", "structlagrange_1_1_stack_vector.html", null ],
    [ "StaticAssertableBool< Args >", "structlagrange_1_1_static_assertable_bool.html", null ],
    [ "StitchingOptions", "structlagrange_1_1texproc_1_1_stitching_options.html", null ],
    [ "SubdividedMeshData< VertexArray, FacetArray >", "structlagrange_1_1legacy_1_1_subdivided_mesh_data.html", null ],
    [ "SubdivisionOptions", "structlagrange_1_1subdivision_1_1_subdivision_options.html", null ],
    [ "SubmeshOptions", "structlagrange_1_1_submesh_options.html", null ],
    [ "SubSelection< ElementType, IndexType >", "structlagrange_1_1ui_1_1_sub_selection.html", null ],
    [ "SurfaceMesh< Scalar_, Index_ >", "classlagrange_1_1_surface_mesh.html", null ],
    [ "SVGSetting", "structlagrange_1_1image__io_1_1_s_v_g_setting.html", null ],
    [ "SweepOptions< Scalar >", "classlagrange_1_1primitive_1_1_sweep_options.html", null ],
    [ "SweepPath< _Scalar >", "classlagrange_1_1primitive_1_1legacy_1_1_sweep_path.html", [
      [ "CircularArcSweepPath< _Scalar >", "classlagrange_1_1primitive_1_1legacy_1_1_circular_arc_sweep_path.html", null ],
      [ "LinearSweepPath< _Scalar >", "classlagrange_1_1primitive_1_1legacy_1_1_linear_sweep_path.html", null ]
    ] ],
    [ "SweepPath< _VertexArray::Scalar >", "classlagrange_1_1primitive_1_1legacy_1_1_sweep_path.html", [
      [ "PolylineSweepPath< _VertexArray >", "classlagrange_1_1primitive_1_1legacy_1_1_polyline_sweep_path.html", null ]
    ] ],
    [ "Systems", "classlagrange_1_1ui_1_1_systems.html", null ],
    [ "TangentBitangentOptions", "structlagrange_1_1_tangent_bitangent_options.html", null ],
    [ "TangentBitangentResult", "structlagrange_1_1_tangent_bitangent_result.html", null ],
    [ "TemporaryLigthVisualization", "structlagrange_1_1ui_1_1_temporary_ligth_visualization.html", null ],
    [ "Texture", "structlagrange_1_1scene_1_1_texture.html", null ],
    [ "Texture", "classlagrange_1_1ui_1_1_texture.html", null ],
    [ "TextureInfo", "structlagrange_1_1scene_1_1_texture_info.html", null ],
    [ "TextureRasterizer< Scalar, Index >", "classlagrange_1_1texproc_1_1_texture_rasterizer.html", null ],
    [ "TextureRasterizerOptions", "structlagrange_1_1texproc_1_1_texture_rasterizer_options.html", null ],
    [ "ThickenAndCloseOptions", "structlagrange_1_1_thicken_and_close_options.html", null ],
    [ "ThreadPool", "structlagrange_1_1filtering_1_1threadpool_1_1_thread_pool.html", null ],
    [ "ThreadPool", "structlagrange_1_1poisson_1_1threadpool_1_1_thread_pool.html", null ],
    [ "ThreadPool", "structlagrange_1_1texproc_1_1threadpool_1_1_thread_pool.html", null ],
    [ "ToolbarPanel", "structlagrange_1_1ui_1_1_toolbar_panel.html", null ],
    [ "Tools", "classlagrange_1_1ui_1_1_tools.html", null ],
    [ "TorusConfig", "structlagrange_1_1primitive_1_1legacy_1_1_torus_config.html", null ],
    [ "Transform", "structlagrange_1_1ui_1_1_texture_1_1_transform.html", null ],
    [ "Transform", "structlagrange_1_1ui_1_1_transform.html", null ],
    [ "TransformChangedEvent", "structlagrange_1_1ui_1_1_transform_changed_event.html", null ],
    [ "TransformOptions", "structlagrange_1_1_transform_options.html", null ],
    [ "TranslateToolTag", "structlagrange_1_1ui_1_1_translate_tool_tag.html", null ],
    [ "TreeNode", "structlagrange_1_1ui_1_1_tree_node.html", null ],
    [ "TriangleAABBTree< Scalar, Index, Dim >", "classlagrange_1_1bvh_1_1_triangle_a_a_b_b_tree.html", null ],
    [ "TriangulationOptions", "structlagrange_1_1_triangulation_options.html", null ],
    [ "true_type", null, [
      [ "is_mesh_helper< MeshType, typename Void< typename MeshType::VertexArray, typename MeshType::FacetArray >::type >", "structlagrange_1_1_mesh_trait_helper_1_1is__mesh__helper_3_01_mesh_type_00_01typename_01_void_3_189721d847f0585e54612704ceb864c0.html", null ],
      [ "is_mesh_smart_ptr_helper< MeshTypePtr, typename Void< typename MeshTypePtr::element_type, typename MeshTypePtr::element_type::VertexArray, typename MeshTypePtr::element_type::FacetArray >::type >", "structlagrange_1_1_mesh_trait_helper_1_1is__mesh__smart__ptr__helper_3_01_mesh_type_ptr_00_01typdd3a1b441f06e428de34247e1df62704.html", null ]
    ] ],
    [ "type_caster< lagrange::scene::Value >", "structtype__caster_3_01lagrange_1_1scene_1_1_value_01_4.html", null ],
    [ "type_traits< T >", "structlagrange_1_1ui_1_1type__traits.html", null ],
    [ "type_traits< double >", "structlagrange_1_1ui_1_1type__traits_3_01double_01_4.html", null ],
    [ "type_traits< float >", "structlagrange_1_1ui_1_1type__traits_3_01float_01_4.html", null ],
    [ "type_traits< int16_t >", "structlagrange_1_1ui_1_1type__traits_3_01int16__t_01_4.html", null ],
    [ "type_traits< int32_t >", "structlagrange_1_1ui_1_1type__traits_3_01int32__t_01_4.html", null ],
    [ "type_traits< int8_t >", "structlagrange_1_1ui_1_1type__traits_3_01int8__t_01_4.html", null ],
    [ "type_traits< uint16_t >", "structlagrange_1_1ui_1_1type__traits_3_01uint16__t_01_4.html", null ],
    [ "type_traits< uint32_t >", "structlagrange_1_1ui_1_1type__traits_3_01uint32__t_01_4.html", null ],
    [ "type_traits< uint8_t >", "structlagrange_1_1ui_1_1type__traits_3_01uint8__t_01_4.html", null ],
    [ "TypeData", "structlagrange_1_1ui_1_1_type_data.html", null ],
    [ "UIPanel", "structlagrange_1_1ui_1_1_u_i_panel.html", null ],
    [ "UIWidget", "classlagrange_1_1ui_1_1_u_i_widget.html", null ],
    [ "UnflipUVOptions", "structlagrange_1_1_unflip_u_v_options.html", null ],
    [ "UnorientedEdge< Index >", "structlagrange_1_1internal_1_1_unoriented_edge.html", null ],
    [ "UserDataConverter", "structlagrange_1_1scene_1_1_user_data_converter.html", null ],
    [ "UVChartOptions", "structlagrange_1_1_u_v_chart_options.html", null ],
    [ "UVDistortionOptions", "structlagrange_1_1_u_v_distortion_options.html", null ],
    [ "UVMeshOptions", "structlagrange_1_1_u_v_mesh_options.html", null ],
    [ "Value", "classlagrange_1_1scene_1_1_value.html", null ],
    [ "value_field< T >", "structlagrange_1_1ui_1_1utils_1_1value__field.html", null ],
    [ "value_field< double >", "structlagrange_1_1ui_1_1utils_1_1value__field_3_01double_01_4.html", null ],
    [ "value_field< float >", "structlagrange_1_1ui_1_1utils_1_1value__field_3_01float_01_4.html", null ],
    [ "value_field< int >", "structlagrange_1_1ui_1_1utils_1_1value__field_3_01int_01_4.html", null ],
    [ "value_ptr< T, Cloner, Deleter >", "classlagrange_1_1value__ptr.html", null ],
    [ "VAO", "structlagrange_1_1ui_1_1_v_a_o.html", null ],
    [ "vector", null, [
      [ "SmallVector< size_t, 2 >", "classlagrange_1_1_small_vector.html", null ],
      [ "SmallVector< int64_t, 2 >", "classlagrange_1_1_small_vector.html", null ],
      [ "SmallVector< Scalar, 3 >", "classlagrange_1_1_small_vector.html", null ],
      [ "SmallVector< T, N >", "classlagrange_1_1_small_vector.html", null ]
    ] ],
    [ "Vector4f", null, [
      [ "Color", "classlagrange_1_1ui_1_1_color.html", null ]
    ] ],
    [ "VerboseTimer", "classlagrange_1_1_verbose_timer.html", null ],
    [ "VertexBuffer", "structlagrange_1_1ui_1_1_vertex_buffer.html", null ],
    [ "VertexData", "structlagrange_1_1ui_1_1_vertex_data.html", null ],
    [ "VertexManifoldOptions", "structlagrange_1_1_vertex_manifold_options.html", null ],
    [ "VertexNormalOptions", "structlagrange_1_1_vertex_normal_options.html", null ],
    [ "VertexValenceOptions", "structlagrange_1_1_vertex_valence_options.html", null ],
    [ "Viewer", "classlagrange_1_1ui_1_1_viewer.html", null ],
    [ "ViewportComponent", "structlagrange_1_1ui_1_1_viewport_component.html", [
      [ "ShadowmappingViewport", "structlagrange_1_1ui_1_1_shadowmapping_viewport.html", null ]
    ] ],
    [ "ViewportPanel", "structlagrange_1_1ui_1_1_viewport_panel.html", null ],
    [ "ViewportTransform", "structlagrange_1_1ui_1_1_camera_1_1_viewport_transform.html", null ],
    [ "Void< Ts >", "structlagrange_1_1_mesh_trait_helper_1_1_void.html", null ],
    [ "VolumeToMeshOptions", "structlagrange_1_1volume_1_1_volume_to_mesh_options.html", null ],
    [ "weak_ptr< T >", "classlagrange_1_1internal_1_1weak__ptr.html", null ],
    [ "WeldOptions", "structlagrange_1_1bvh_1_1_weld_options.html", null ],
    [ "WindowCloseEvent", "structlagrange_1_1ui_1_1_window_close_event.html", null ],
    [ "WindowDropEvent", "structlagrange_1_1ui_1_1_window_drop_event.html", null ],
    [ "WindowOptions", "structlagrange_1_1ui_1_1_viewer_1_1_window_options.html", null ],
    [ "WindowResizeEvent", "structlagrange_1_1ui_1_1_window_resize_event.html", null ],
    [ "WindowSize", "structlagrange_1_1ui_1_1_window_size.html", null ]
];