var hierarchy =
[
    [ "AcceleratedPicking", "structlagrange_1_1ui_1_1_accelerated_picking.html", null ],
    [ "AdjacencyList< Index >", "classlagrange_1_1_adjacency_list.html", null ],
    [ "AlignedBox3f", null, [
      [ "AABB", "classlagrange_1_1ui_1_1_a_a_b_b.html", null ]
    ] ],
    [ "Args", "struct_args.html", null ],
    [ "args_to_tuple< Args >", "structlagrange_1_1ui_1_1detail_1_1args__to__tuple.html", null ],
    [ "ArrayBase", "classlagrange_1_1experimental_1_1_array_base.html", [
      [ "EigenArray< _EigenType >", "classlagrange_1_1experimental_1_1_eigen_array.html", null ],
      [ "EigenArrayRef< _EigenType, false >", "classlagrange_1_1experimental_1_1_eigen_array_ref_3_01___eigen_type_00_01false_01_4.html", null ],
      [ "EigenArrayRef< _EigenType, true >", "classlagrange_1_1experimental_1_1_eigen_array_ref_3_01___eigen_type_00_01true_01_4.html", null ],
      [ "RawArray< _Scalar, _Rows, _Cols, _Options, false >", "classlagrange_1_1experimental_1_1_raw_array_3_01___scalar_00_01___rows_00_01___cols_00_01___options_00_01false_01_4.html", null ],
      [ "RawArray< _Scalar, _Rows, _Cols, _Options, true >", "classlagrange_1_1experimental_1_1_raw_array_3_01___scalar_00_01___rows_00_01___cols_00_01___options_00_01true_01_4.html", null ]
    ] ],
    [ "ArraySerialization< T >", "structlagrange_1_1experimental_1_1internal_1_1_array_serialization.html", null ],
    [ "AsFunction< T >", "structlagrange_1_1ui_1_1util_1_1_as_function.html", null ],
    [ "AsFunction< ReturnType(*)(Arg)>", "structlagrange_1_1ui_1_1util_1_1_as_function_3_01_return_type_07_5_08_07_arg_08_4.html", null ],
    [ "AsFunction< ReturnType(Arg) const >", "structlagrange_1_1ui_1_1util_1_1_as_function_3_01_return_type_07_arg_08_01const_01_4.html", null ],
    [ "AsFunction< ReturnType(Class::*)(Arg) const >", "structlagrange_1_1ui_1_1util_1_1_as_function_3_01_return_type_07_class_1_1_5_08_07_arg_08_01const_01_4.html", null ],
    [ "Attribute", "classlagrange_1_1experimental_1_1_attribute.html", null ],
    [ "AttributeBase", "classlagrange_1_1_attribute_base.html", [
      [ "Attribute< ValueType >", "classlagrange_1_1_attribute.html", null ],
      [ "Attribute< Index >", "classlagrange_1_1_attribute.html", null ],
      [ "Attribute< ValueType_ >", "classlagrange_1_1_attribute.html", null ],
      [ "IndexedAttribute< ValueType_, Index_ >", "classlagrange_1_1_indexed_attribute.html", null ]
    ] ],
    [ "AttributeManager", "classlagrange_1_1experimental_1_1_attribute_manager.html", null ],
    [ "AttributeName", "structlagrange_1_1_attribute_name.html", null ],
    [ "AttributeRender", "structlagrange_1_1ui_1_1_attribute_render.html", null ],
    [ "Attributes< _AttributeArray >", "classlagrange_1_1_attributes.html", null ],
    [ "base_sink", null, [
      [ "PythonLoggingSink", "classlagrange_1_1python_1_1_python_logging_sink.html", null ]
    ] ],
    [ "BitField< EnumType_ >", "classlagrange_1_1_bit_field.html", null ],
    [ "bitset", null, [
      [ "Layer", "structlagrange_1_1ui_1_1_layer.html", null ]
    ] ],
    [ "Bounds", "structlagrange_1_1ui_1_1_bounds.html", null ],
    [ "BucketSortResult< Index >", "structlagrange_1_1internal_1_1_bucket_sort_result.html", null ],
    [ "BVH< _VertexArray, _ElementArray >", "classlagrange_1_1bvh_1_1_b_v_h.html", null ],
    [ "BVH< _VertexArray, lagrange::Triangles >", "classlagrange_1_1bvh_1_1_b_v_h.html", [
      [ "AABBIGL< _VertexArray, _ElementArray >", "classlagrange_1_1bvh_1_1_a_a_b_b_i_g_l.html", null ],
      [ "BVHNanoflann< _VertexArray, _ElementArray >", "classlagrange_1_1bvh_1_1_b_v_h_nanoflann.html", null ]
    ] ],
    [ "Camera", "classlagrange_1_1ui_1_1_camera.html", null ],
    [ "CameraChangedEvent", "structlagrange_1_1ui_1_1_camera_changed_event.html", null ],
    [ "CameraController", "structlagrange_1_1ui_1_1_camera_controller.html", null ],
    [ "CameraFocusAndFit", "structlagrange_1_1ui_1_1_camera_focus_and_fit.html", null ],
    [ "CameraTurntable", "structlagrange_1_1ui_1_1_camera_turntable.html", null ],
    [ "ChainEdgesOptions", "structlagrange_1_1_chain_edges_options.html", null ],
    [ "ChainEdgesResult< Index >", "structlagrange_1_1_chain_edges_result.html", null ],
    [ "BVH< _VertexArray, _ElementArray >::ClosestPoint", "structlagrange_1_1bvh_1_1_b_v_h_1_1_closest_point.html", null ],
    [ "ClosestPointResult< Scalar >", "structlagrange_1_1raycasting_1_1_closest_point_result.html", null ],
    [ "ColormapShaderMode", "structlagrange_1_1ui_1_1_colormap_shader_mode.html", null ],
    [ "ComponentOptions", "structlagrange_1_1_component_options.html", null ],
    [ "ComponentPanel", "structlagrange_1_1ui_1_1_component_panel.html", null ],
    [ "Components< GeometryType >", "classlagrange_1_1legacy_1_1_components.html", null ],
    [ "ComputeBorderedComponentsOutput< Index >", "structlagrange_1_1legacy_1_1_compute_bordered_components_output.html", null ],
    [ "ComputeMeshCentroidOutput< Scalar >", "structlagrange_1_1legacy_1_1_compute_mesh_centroid_output.html", null ],
    [ "ComputePointcloudPCAOutput< Scalar >", "structlagrange_1_1_compute_pointcloud_p_c_a_output.html", null ],
    [ "Connectivity< GeometryType >", "classlagrange_1_1_connectivity.html", null ],
    [ "control_block_base", "classlagrange_1_1internal_1_1control__block__base.html", [
      [ "control_block< T, D >", "classlagrange_1_1internal_1_1control__block.html", null ]
    ] ],
    [ "convert_implicit< T >", "structlagrange_1_1ui_1_1detail_1_1convert__implicit.html", null ],
    [ "copy_on_write_ptr< T >", "classlagrange_1_1copy__on__write__ptr.html", null ],
    [ "CornerNormalOptions", "structlagrange_1_1_corner_normal_options.html", null ],
    [ "CreateOptions", "structlagrange_1_1testing_1_1_create_options.html", null ],
    [ "VertexBuffer::DataDescription", "structlagrange_1_1ui_1_1_vertex_buffer_1_1_data_description.html", null ],
    [ "default_delete< T >", "classlagrange_1_1internal_1_1default__delete.html", null ],
    [ "default_delete< T[]>", "classlagrange_1_1internal_1_1default__delete_3_01_t_0f_0e_4.html", null ],
    [ "DefaultLayers", "structlagrange_1_1ui_1_1_default_layers.html", null ],
    [ "DefaultPanels", "structlagrange_1_1ui_1_1_default_panels.html", null ],
    [ "DefaultShaderAtrribNames", "structlagrange_1_1ui_1_1_default_shader_atrrib_names.html", null ],
    [ "DefaultShaderIndicesNames", "structlagrange_1_1ui_1_1_default_shader_indices_names.html", null ],
    [ "DefaultShaders", "structlagrange_1_1ui_1_1_default_shaders.html", null ],
    [ "DefaultSystems", "structlagrange_1_1ui_1_1_default_systems.html", null ],
    [ "DefaultTools", "structlagrange_1_1ui_1_1_default_tools.html", null ],
    [ "DehoveredEvent", "structlagrange_1_1ui_1_1_dehovered_event.html", null ],
    [ "DeselectedEvent", "structlagrange_1_1ui_1_1_deselected_event.html", null ],
    [ "DihedralAngleOptions", "structlagrange_1_1_dihedral_angle_options.html", null ],
    [ "DijkstraDistanceOptions< Scalar, Index >", "structlagrange_1_1_dijkstra_distance_options.html", null ],
    [ "DisjointSets< IndexType >", "classlagrange_1_1_disjoint_sets.html", [
      [ "DisjointSetsWithSize< IndexType >", "classlagrange_1_1_disjoint_sets_with_size.html", null ]
    ] ],
    [ "Dockspace", "structlagrange_1_1ui_1_1_dockspace.html", null ],
    [ "Texture::DownloadResult", "structlagrange_1_1ui_1_1_texture_1_1_download_result.html", null ],
    [ "Earcut< N >", "classlagrange_1_1mapbox_1_1detail_1_1_earcut.html", null ],
    [ "EdgeAABBTree< VertexArray, EdgeArray, DIM >", "structlagrange_1_1bvh_1_1_edge_a_a_b_b_tree.html", null ],
    [ "EdgeLengthOptions", "structlagrange_1_1_edge_length_options.html", null ],
    [ "EdgeType< Index >", "classlagrange_1_1_edge_type.html", null ],
    [ "EigenArrayRef< _EigenType, IsConst >", "classlagrange_1_1experimental_1_1_eigen_array_ref.html", null ],
    [ "ElementEdge", "structlagrange_1_1ui_1_1_element_edge.html", null ],
    [ "ElementFace", "structlagrange_1_1ui_1_1_element_face.html", null ],
    [ "ElementObject", "structlagrange_1_1ui_1_1_element_object.html", null ],
    [ "ElementVertex", "structlagrange_1_1ui_1_1_element_vertex.html", null ],
    [ "EmbreeRayCaster< ScalarType >", "classlagrange_1_1raycasting_1_1_embree_ray_caster.html", null ],
    [ "emitter", null, [
      [ "EventEmitter", "structlagrange_1_1ui_1_1_event_emitter.html", null ]
    ] ],
    [ "EnumToScalar< type >", "structlagrange_1_1experimental_1_1_enum_to_scalar.html", null ],
    [ "EnumToScalar< ScalarEnum::DOUBLE >", "structlagrange_1_1experimental_1_1_enum_to_scalar_3_01_scalar_enum_1_1_d_o_u_b_l_e_01_4.html", null ],
    [ "EnumToScalar< ScalarEnum::FLOAT >", "structlagrange_1_1experimental_1_1_enum_to_scalar_3_01_scalar_enum_1_1_f_l_o_a_t_01_4.html", null ],
    [ "EnumToScalar< ScalarEnum::INT16 >", "structlagrange_1_1experimental_1_1_enum_to_scalar_3_01_scalar_enum_1_1_i_n_t16_01_4.html", null ],
    [ "EnumToScalar< ScalarEnum::INT32 >", "structlagrange_1_1experimental_1_1_enum_to_scalar_3_01_scalar_enum_1_1_i_n_t32_01_4.html", null ],
    [ "EnumToScalar< ScalarEnum::INT64 >", "structlagrange_1_1experimental_1_1_enum_to_scalar_3_01_scalar_enum_1_1_i_n_t64_01_4.html", null ],
    [ "EnumToScalar< ScalarEnum::INT8 >", "structlagrange_1_1experimental_1_1_enum_to_scalar_3_01_scalar_enum_1_1_i_n_t8_01_4.html", null ],
    [ "EnumToScalar< ScalarEnum::UINT16 >", "structlagrange_1_1experimental_1_1_enum_to_scalar_3_01_scalar_enum_1_1_u_i_n_t16_01_4.html", null ],
    [ "EnumToScalar< ScalarEnum::UINT32 >", "structlagrange_1_1experimental_1_1_enum_to_scalar_3_01_scalar_enum_1_1_u_i_n_t32_01_4.html", null ],
    [ "EnumToScalar< ScalarEnum::UINT64 >", "structlagrange_1_1experimental_1_1_enum_to_scalar_3_01_scalar_enum_1_1_u_i_n_t64_01_4.html", null ],
    [ "EnumToScalar< ScalarEnum::UINT8 >", "structlagrange_1_1experimental_1_1_enum_to_scalar_3_01_scalar_enum_1_1_u_i_n_t8_01_4.html", null ],
    [ "ExactPredicates", "classlagrange_1_1_exact_predicates.html", [
      [ "ExactPredicatesShewchuk", "classlagrange_1_1_exact_predicates_shewchuk.html", null ]
    ] ],
    [ "FacetAreaOptions", "structlagrange_1_1_facet_area_options.html", null ],
    [ "FacetCentroidOptions", "structlagrange_1_1_facet_centroid_options.html", null ],
    [ "FacetNormalOptions", "structlagrange_1_1_facet_normal_options.html", null ],
    [ "false_type", null, [
      [ "is_mesh_helper< T, _ >", "structlagrange_1_1_mesh_trait_helper_1_1is__mesh__helper.html", null ],
      [ "is_mesh_smart_ptr_helper< T, _ >", "structlagrange_1_1_mesh_trait_helper_1_1is__mesh__smart__ptr__helper.html", null ]
    ] ],
    [ "FastWindingNumber", "classlagrange_1_1winding_1_1_fast_winding_number.html", null ],
    [ "FileDialogPath", "classlagrange_1_1ui_1_1_file_dialog_path.html", null ],
    [ "FileDialogPath::FileDialogPathImpl", "structlagrange_1_1ui_1_1_file_dialog_path_1_1_file_dialog_path_impl.html", null ],
    [ "FileFilter", "structlagrange_1_1ui_1_1_file_filter.html", null ],
    [ "FocusedViewportPanel", "structlagrange_1_1ui_1_1_focused_viewport_panel.html", null ],
    [ "Formatter", null, [
      [ "ColorFormatter", "classlagrange_1_1__logging_1_1_color_formatter.html", null ]
    ] ],
    [ "FrameBuffer", "classlagrange_1_1ui_1_1_frame_buffer.html", null ],
    [ "Frustum", "classlagrange_1_1ui_1_1_frustum.html", null ],
    [ "function_ref< F >", "classlagrange_1_1function__ref.html", null ],
    [ "function_ref< R(Args...)>", "classlagrange_1_1function__ref_3_01_r_07_args_8_8_8_08_4.html", null ],
    [ "GizmoContext", "structlagrange_1_1ui_1_1_gizmo_context.html", null ],
    [ "GizmoObjectTransform", "structlagrange_1_1ui_1_1_gizmo_object_transform.html", null ],
    [ "GLMesh", "structlagrange_1_1ui_1_1_g_l_mesh.html", null ],
    [ "GlobalTime", "structlagrange_1_1ui_1_1_global_time.html", null ],
    [ "GLQuery", "structlagrange_1_1ui_1_1_g_l_query.html", null ],
    [ "GLRenderQueueItem", "structlagrange_1_1ui_1_1_g_l_render_queue_item.html", null ],
    [ "GLScope", "structlagrange_1_1ui_1_1_g_l_scope.html", null ],
    [ "GLState", "structlagrange_1_1ui_1_1_g_l_state.html", null ],
    [ "GPUBuffer", "structlagrange_1_1ui_1_1_g_p_u_buffer.html", null ],
    [ "hash< lagrange::EdgeType< Index > >", "structstd_1_1hash_3_01lagrange_1_1_edge_type_3_01_index_01_4_01_4.html", null ],
    [ "Hovered", "structlagrange_1_1ui_1_1_hovered.html", null ],
    [ "HoveredEvent", "structlagrange_1_1ui_1_1_hovered_event.html", null ],
    [ "HoveredTemp", "structlagrange_1_1ui_1_1_hovered_temp.html", null ],
    [ "IBL", "structlagrange_1_1ui_1_1_i_b_l.html", null ],
    [ "IBLChangedEvent", "structlagrange_1_1ui_1_1_i_b_l_changed_event.html", null ],
    [ "ImmediateEntities", "structlagrange_1_1ui_1_1_immediate_entities.html", null ],
    [ "FastWindingNumber::Impl", "structlagrange_1_1winding_1_1_fast_winding_number_1_1_impl.html", null ],
    [ "IndexedAttribute", "classlagrange_1_1experimental_1_1_indexed_attribute.html", null ],
    [ "IndexedAttributeManager", "classlagrange_1_1experimental_1_1_indexed_attribute_manager.html", null ],
    [ "IndexedAttributes< _AttributeArray, _IndexArray >", "classlagrange_1_1_indexed_attributes.html", null ],
    [ "InputState", "structlagrange_1_1ui_1_1_input_state.html", null ],
    [ "EdgeType< Index >::iterator", "classlagrange_1_1_edge_type_1_1iterator.html", null ],
    [ "Keybinds::Keybind", "structlagrange_1_1ui_1_1_keybinds_1_1_keybind.html", null ],
    [ "Keybinds", "classlagrange_1_1ui_1_1_keybinds.html", null ],
    [ "lambda_helper< F >", "structlagrange_1_1ui_1_1util_1_1lambda__helper.html", null ],
    [ "lambda_helper< Result(F::*)(Args...) const >", "structlagrange_1_1ui_1_1util_1_1lambda__helper_3_01_result_07_f_1_1_5_08_07_args_8_8_8_08_01const_01_4.html", null ],
    [ "LastTool", "structlagrange_1_1ui_1_1_last_tool.html", null ],
    [ "LightComponent", "structlagrange_1_1ui_1_1_light_component.html", null ],
    [ "LightComponentChangedEvent", "structlagrange_1_1ui_1_1_light_component_changed_event.html", null ],
    [ "list_caster", null, [
      [ "type_caster< lagrange::StackVector< T, N > >", "structtype__caster_3_01lagrange_1_1_stack_vector_3_01_t_00_01_n_01_4_01_4.html", null ]
    ] ],
    [ "LoadOptions", "structlagrange_1_1io_1_1_load_options.html", null ],
    [ "LogData", "classlagrange_1_1ui_1_1_log_data.html", null ],
    [ "LoggerContextData", "structlagrange_1_1ui_1_1_logger_context_data.html", null ],
    [ "LoggerPanel", "structlagrange_1_1ui_1_1_logger_panel.html", null ],
    [ "MainMenuHeight", "structlagrange_1_1ui_1_1_main_menu_height.html", null ],
    [ "MapAttributesOptions", "structlagrange_1_1internal_1_1_map_attributes_options.html", null ],
    [ "MarchingTrianglesOutput< MeshType_ >", "structlagrange_1_1_marching_triangles_output.html", null ],
    [ "Material", "classlagrange_1_1ui_1_1_material.html", null ],
    [ "MeshAdapter< MeshType >", "classlagrange_1_1volume_1_1legacy_1_1_mesh_adapter.html", null ],
    [ "MeshAreaOptions", "structlagrange_1_1_mesh_area_options.html", null ],
    [ "MeshBase", "classlagrange_1_1_mesh_base.html", [
      [ "Mesh< _VertexArray, _FacetArray >", "classlagrange_1_1_mesh.html", null ]
    ] ],
    [ "MeshCentroidOptions", "structlagrange_1_1_mesh_centroid_options.html", null ],
    [ "MeshData", "structlagrange_1_1ui_1_1_mesh_data.html", null ],
    [ "MeshDataDirty", "structlagrange_1_1ui_1_1_mesh_data_dirty.html", null ],
    [ "MeshGeometry< _VertexArray, _FacetArray >", "classlagrange_1_1_mesh_geometry.html", [
      [ "ActingMeshGeometry< _VertexArray, _FacetArray >", "classlagrange_1_1_acting_mesh_geometry.html", null ],
      [ "GenuineMeshGeometry< _VertexArray, _FacetArray >", "classlagrange_1_1_genuine_mesh_geometry.html", null ]
    ] ],
    [ "MeshGeometry", "structlagrange_1_1ui_1_1_mesh_geometry.html", null ],
    [ "MeshInstance< Scalar, Index, Dimension >", "structlagrange_1_1scene_1_1_mesh_instance.html", null ],
    [ "MeshLoaderParams", "structlagrange_1_1io_1_1legacy_1_1_mesh_loader_params.html", null ],
    [ "MeshLoaderResult< MeshType >", "structlagrange_1_1io_1_1legacy_1_1_mesh_loader_result.html", null ],
    [ "MeshMapping< MeshType >", "structlagrange_1_1legacy_1_1_mesh_mapping.html", [
      [ "BackwardMeshMapping< MeshType >", "structlagrange_1_1legacy_1_1_backward_mesh_mapping.html", null ],
      [ "ForwardMeshMapping< MeshType >", "structlagrange_1_1legacy_1_1_forward_mesh_mapping.html", null ]
    ] ],
    [ "MeshNavigation< MeshType >", "classlagrange_1_1_mesh_navigation.html", null ],
    [ "MeshRender", "structlagrange_1_1ui_1_1_mesh_render.html", null ],
    [ "MeshRenderChangedEvent", "structlagrange_1_1ui_1_1_mesh_render_changed_event.html", null ],
    [ "MeshSelectionRender", "structlagrange_1_1ui_1_1_mesh_selection_render.html", null ],
    [ "MeshTopology< MeshType >", "classlagrange_1_1legacy_1_1_mesh_topology.html", null ],
    [ "MeshToVolumeOptions", "structlagrange_1_1volume_1_1_mesh_to_volume_options.html", null ],
    [ "MeshTrait< MeshType_ >", "structlagrange_1_1_mesh_trait.html", null ],
    [ "InputState::Mouse", "structlagrange_1_1ui_1_1_input_state_1_1_mouse.html", null ],
    [ "EdgeAABBTree< VertexArray, EdgeArray, DIM >::Node", "structlagrange_1_1bvh_1_1_edge_a_a_b_b_tree_1_1_node.html", null ],
    [ "NormalOptions", "structlagrange_1_1_normal_options.html", null ],
    [ "nth< I, T >", "structlagrange_1_1mapbox_1_1util_1_1nth.html", null ],
    [ "ObjectIDViewport", "structlagrange_1_1ui_1_1_object_i_d_viewport.html", null ],
    [ "ObjReaderResult< Scalar, Index >", "structlagrange_1_1io_1_1internal_1_1_obj_reader_result.html", null ],
    [ "OrderedPairHash< T, Enable >", "structlagrange_1_1_ordered_pair_hash.html", null ],
    [ "OrderedPairHash< std::pair< U, V > >", "structlagrange_1_1_ordered_pair_hash_3_01std_1_1pair_3_01_u_00_01_v_01_4_01_4.html", null ],
    [ "OSDUV< MeshType >", "structlagrange_1_1subdivision_1_1internal_1_1_o_s_d_u_v.html", null ],
    [ "OSDVertex< MeshType >", "structlagrange_1_1subdivision_1_1internal_1_1_o_s_d_vertex.html", null ],
    [ "PaginatedMatrixWidget", "classlagrange_1_1ui_1_1_paginated_matrix_widget.html", null ],
    [ "pair_hash", "structlagrange_1_1ui_1_1utils_1_1pair__hash.html", null ],
    [ "Texture::Params", "structlagrange_1_1ui_1_1_texture_1_1_params.html", null ],
    [ "PayloadComponent", "structlagrange_1_1ui_1_1_payload_component.html", null ],
    [ "PayloadEntity", "structlagrange_1_1ui_1_1_payload_entity.html", null ],
    [ "PBRMaterial", "structlagrange_1_1ui_1_1_p_b_r_material.html", null ],
    [ "PostProcessQuadVertexData", "structlagrange_1_1ui_1_1_post_process_quad_vertex_data.html", null ],
    [ "ProgressCallback", "classlagrange_1_1_progress_callback.html", null ],
    [ "ptr< T, D >", "classlagrange_1_1internal_1_1ptr.html", null ],
    [ "ptr< T, default_delete< T > >", "classlagrange_1_1internal_1_1ptr.html", null ],
    [ "PyAttribute", "classlagrange_1_1python_1_1_py_attribute.html", null ],
    [ "PyIndexedAttribute", "classlagrange_1_1python_1_1_py_indexed_attribute.html", null ],
    [ "RasterizerOptions", "structlagrange_1_1ui_1_1_rasterizer_options.html", null ],
    [ "RawArray< _Scalar, _Rows, _Cols, _Options, IsConst >", "classlagrange_1_1experimental_1_1_raw_array.html", null ],
    [ "Camera::Ray", "structlagrange_1_1ui_1_1_camera_1_1_ray.html", null ],
    [ "RaycasterMesh", "classlagrange_1_1raycasting_1_1_raycaster_mesh.html", [
      [ "RaycasterMeshDerived< MeshType >", "classlagrange_1_1raycasting_1_1_raycaster_mesh_derived.html", null ]
    ] ],
    [ "RayFacetHit", "structlagrange_1_1ui_1_1_ray_facet_hit.html", null ],
    [ "RemapVerticesOptions", "structlagrange_1_1_remap_vertices_options.html", null ],
    [ "RemeshingOptions", "structlagrange_1_1scene_1_1_remeshing_options.html", null ],
    [ "RemoveDuplicateVerticesOptions", "structlagrange_1_1_remove_duplicate_vertices_options.html", null ],
    [ "RemoveNullAreaFacetsOptions", "structlagrange_1_1_remove_null_area_facets_options.html", null ],
    [ "RenderContext", "structlagrange_1_1ui_1_1_render_context.html", null ],
    [ "resource_loader", null, [
      [ "ShaderLoader", "structlagrange_1_1ui_1_1_shader_loader.html", null ]
    ] ],
    [ "RotateToolTag", "structlagrange_1_1ui_1_1_rotate_tool_tag.html", null ],
    [ "runtime_error", null, [
      [ "Error", "structlagrange_1_1_error.html", [
        [ "BadCastError", "structlagrange_1_1_bad_cast_error.html", null ]
      ] ],
      [ "ShaderException", "classlagrange_1_1ui_1_1_shader_exception.html", null ]
    ] ],
    [ "SamplePointsOnSurfaceOutput< MeshType >", "structlagrange_1_1_sample_points_on_surface_output.html", null ],
    [ "SaveOptions", "structlagrange_1_1io_1_1_save_options.html", null ],
    [ "ScalarToEnum< T, T2 >", "structlagrange_1_1experimental_1_1_scalar_to_enum.html", null ],
    [ "ScalarToEnum< double, void >", "structlagrange_1_1experimental_1_1_scalar_to_enum_3_01double_00_01void_01_4.html", null ],
    [ "ScalarToEnum< float, void >", "structlagrange_1_1experimental_1_1_scalar_to_enum_3_01float_00_01void_01_4.html", null ],
    [ "ScalarToEnum< int16_t, void >", "structlagrange_1_1experimental_1_1_scalar_to_enum_3_01int16__t_00_01void_01_4.html", null ],
    [ "ScalarToEnum< int32_t, void >", "structlagrange_1_1experimental_1_1_scalar_to_enum_3_01int32__t_00_01void_01_4.html", null ],
    [ "ScalarToEnum< int64_t, void >", "structlagrange_1_1experimental_1_1_scalar_to_enum_3_01int64__t_00_01void_01_4.html", null ],
    [ "ScalarToEnum< int8_t, void >", "structlagrange_1_1experimental_1_1_scalar_to_enum_3_01int8__t_00_01void_01_4.html", null ],
    [ "ScalarToEnum< uint16_t, void >", "structlagrange_1_1experimental_1_1_scalar_to_enum_3_01uint16__t_00_01void_01_4.html", null ],
    [ "ScalarToEnum< uint32_t, void >", "structlagrange_1_1experimental_1_1_scalar_to_enum_3_01uint32__t_00_01void_01_4.html", null ],
    [ "ScalarToEnum< uint64_t, void >", "structlagrange_1_1experimental_1_1_scalar_to_enum_3_01uint64__t_00_01void_01_4.html", null ],
    [ "ScalarToEnum< uint8_t, void >", "structlagrange_1_1experimental_1_1_scalar_to_enum_3_01uint8__t_00_01void_01_4.html", null ],
    [ "ScaleToolTag", "structlagrange_1_1ui_1_1_scale_tool_tag.html", null ],
    [ "ScenePanel", "structlagrange_1_1ui_1_1_scene_panel.html", null ],
    [ "ScopedLogLevel", "classlagrange_1_1_scoped_log_level.html", null ],
    [ "ScopedTimer", "classlagrange_1_1_scoped_timer.html", null ],
    [ "Selected", "structlagrange_1_1ui_1_1_selected.html", null ],
    [ "SelectedEvent", "structlagrange_1_1ui_1_1_selected_event.html", null ],
    [ "SelectFacetsByNormalSimilarityParameters< MeshType >", "structlagrange_1_1_select_facets_by_normal_similarity_parameters.html", null ],
    [ "SelectionContext", "structlagrange_1_1ui_1_1_selection_context.html", null ],
    [ "SelectionViewport", "structlagrange_1_1ui_1_1_selection_viewport.html", null ],
    [ "SelectToolTag", "structlagrange_1_1ui_1_1_select_tool_tag.html", null ],
    [ "SeparateByComponentsOptions", "structlagrange_1_1_separate_by_components_options.html", null ],
    [ "SeparateByFacetGroupsOptions", "structlagrange_1_1_separate_by_facet_groups_options.html", null ],
    [ "Shader", "classlagrange_1_1ui_1_1_shader.html", null ],
    [ "ShaderDefinition", "structlagrange_1_1ui_1_1_shader_definition.html", null ],
    [ "ShaderProperty< T >", "structlagrange_1_1ui_1_1_shader_property.html", null ],
    [ "ShaderProperty< bool >", "structlagrange_1_1ui_1_1_shader_property.html", [
      [ "ShaderBoolProperty", "structlagrange_1_1ui_1_1_shader_bool_property.html", null ]
    ] ],
    [ "ShaderProperty< Color >", "structlagrange_1_1ui_1_1_shader_property.html", [
      [ "ShaderColorProperty", "structlagrange_1_1ui_1_1_shader_color_property.html", null ]
    ] ],
    [ "ShaderProperty< Eigen::Vector4f >", "structlagrange_1_1ui_1_1_shader_property.html", [
      [ "ShaderVectorProperty", "structlagrange_1_1ui_1_1_shader_vector_property.html", null ]
    ] ],
    [ "ShaderProperty< float >", "structlagrange_1_1ui_1_1_shader_property.html", [
      [ "ShaderFloatProperty", "structlagrange_1_1ui_1_1_shader_float_property.html", null ]
    ] ],
    [ "ShaderProperty< int >", "structlagrange_1_1ui_1_1_shader_property.html", [
      [ "ShaderIntProperty", "structlagrange_1_1ui_1_1_shader_int_property.html", null ]
    ] ],
    [ "ShaderProperty< ShaderTextureValue >", "structlagrange_1_1ui_1_1_shader_property.html", [
      [ "ShaderTextureProperty", "structlagrange_1_1ui_1_1_shader_texture_property.html", null ]
    ] ],
    [ "ShaderTextureValue", "structlagrange_1_1ui_1_1_shader_texture_value.html", null ],
    [ "ShaderValue", "structlagrange_1_1ui_1_1_shader_value.html", null ],
    [ "ShadowMap", "structlagrange_1_1ui_1_1_shadow_map.html", null ],
    [ "ShadowMapFBO", "structlagrange_1_1ui_1_1_shadow_map_f_b_o.html", null ],
    [ "shared_ptr_access< T, bool, bool >", "classlagrange_1_1internal_1_1shared__ptr__access.html", [
      [ "shared_ptr< T >", "classlagrange_1_1internal_1_1shared__ptr.html", null ]
    ] ],
    [ "shared_ptr_access< T, false, true >", "classlagrange_1_1internal_1_1shared__ptr__access_3_01_t_00_01false_00_01true_01_4.html", null ],
    [ "shared_ptr_access< T, true, false >", "classlagrange_1_1internal_1_1shared__ptr__access_3_01_t_00_01true_00_01false_01_4.html", null ],
    [ "SharedSpan< T >", "classlagrange_1_1_shared_span.html", null ],
    [ "SilentMultiTimer", "classlagrange_1_1_silent_multi_timer.html", null ],
    [ "SilentTimer", "classlagrange_1_1_silent_timer.html", null ],
    [ "SimpleScene< Scalar, Index, Dimension >", "classlagrange_1_1scene_1_1_simple_scene.html", null ],
    [ "SkinningExtractNResult< Scalar, Index >", "structlagrange_1_1internal_1_1_skinning_extract_n_result.html", null ],
    [ "SkyboxCubeVertexData", "structlagrange_1_1ui_1_1_skybox_cube_vertex_data.html", null ],
    [ "StackSet< T, N >", "structlagrange_1_1_stack_set.html", null ],
    [ "StackVector< T, N >", "structlagrange_1_1_stack_vector.html", null ],
    [ "StaticAssertableBool< Args >", "structlagrange_1_1_static_assertable_bool.html", null ],
    [ "string", null, [
      [ "Name", "structlagrange_1_1ui_1_1_name.html", null ]
    ] ],
    [ "SubmeshOptions", "structlagrange_1_1_submesh_options.html", null ],
    [ "SubSelection< ElementType, IndexType >", "structlagrange_1_1ui_1_1_sub_selection.html", null ],
    [ "SurfaceMesh< Scalar_, Index_ >", "classlagrange_1_1_surface_mesh.html", null ],
    [ "SurfaceMesh< Scalar, Index >", "classlagrange_1_1_surface_mesh.html", null ],
    [ "Systems", "classlagrange_1_1ui_1_1_systems.html", null ],
    [ "TangentBitangentOptions", "structlagrange_1_1_tangent_bitangent_options.html", null ],
    [ "TangentBitangentResult", "structlagrange_1_1_tangent_bitangent_result.html", null ],
    [ "TemporaryLigthVisualization", "structlagrange_1_1ui_1_1_temporary_ligth_visualization.html", null ],
    [ "TestAttribute", "classtests_1_1test__attribute_1_1_test_attribute.html", null ],
    [ "TestCombineMeshes", "classtests_1_1test__combine__meshes_1_1_test_combine_meshes.html", null ],
    [ "TestComputeCentroid", "classtests_1_1test__compute__centroid_1_1_test_compute_centroid.html", null ],
    [ "TestComputeComponents", "classtests_1_1test__compute__components_1_1_test_compute_components.html", null ],
    [ "TestComputeDihedralAngles", "classtests_1_1test__compute__dihedral__angles_1_1_test_compute_dihedral_angles.html", null ],
    [ "TestComputeEdgeLengths", "classtests_1_1test__compute__edge__lengths_1_1_test_compute_edge_lengths.html", null ],
    [ "TestComputeFacetArea", "classtests_1_1test__compute__facet__area_1_1_test_compute_facet_area.html", null ],
    [ "TestComputeFacetNormal", "classtests_1_1test__compute__facet__normal_1_1_test_compute_facet_normal.html", null ],
    [ "TestComputeNormal", "classtests_1_1test__compute__normal_1_1_test_compute_normal.html", null ],
    [ "TestComputeTangentBitangent", "classtests_1_1test__compute__tangent__bitangent_1_1_test_compute_tangent_bitangent.html", null ],
    [ "TestComputeVertexNormal", "classtests_1_1test__compute__vertex__normal_1_1_test_compute_vertex_normal.html", null ],
    [ "TestComputeVertexValence", "classtests_1_1test__compute__vertex__valence_1_1_test_compute_vertex_valence.html", null ],
    [ "TestDetectDegenerateFacets", "classtests_1_1test__detect__degenerate__facets_1_1_test_detect_degenerate_facets.html", null ],
    [ "TestIndexedAttribute", "classtests_1_1test__indexed__attribute_1_1_test_indexed_attribute.html", null ],
    [ "TestIO", "classtest__io_1_1_test_i_o.html", null ],
    [ "TestMeshInstance", "classtest__mesh__instance_1_1_test_mesh_instance.html", null ],
    [ "TestNormalizeMeshes", "classtests_1_1test__normalize__meshes_1_1_test_normalize_meshes.html", null ],
    [ "TestPermuteFacets", "classtests_1_1test__permute__facets_1_1_test_permute_facets.html", null ],
    [ "TestPermuteVertices", "classtests_1_1test__permute__vertices_1_1_test_permute_vertices.html", null ],
    [ "TestRemapVertices", "classtests_1_1test__remap__vertices_1_1_test_remap_vertices.html", null ],
    [ "TestRemoveDuplicateVertices", "classtests_1_1test__remove__duplicate__vertices_1_1_test_remove_duplicate_vertices.html", null ],
    [ "TestRemoveNullAreaFacets", "classtests_1_1test__remove__null__area__facets_1_1_test_remove_null_area_facets.html", null ],
    [ "TestSimpleScene", "classtest__simple__scene_1_1_test_simple_scene.html", null ],
    [ "TestSurfaceMesh", "classtests_1_1test__surface__mesh_1_1_test_surface_mesh.html", null ],
    [ "TestTriangulatePolygonalFacets", "classtests_1_1test__triangulate__polygonal__facets_1_1_test_triangulate_polygonal_facets.html", null ],
    [ "TestUnifyIndexBuffer", "classtests_1_1test__unify__index__buffer_1_1_test_unify_index_buffer.html", null ],
    [ "TestWeldIndexedAttribute", "classtests_1_1test__weld__indexed__attribute_1_1_test_weld_indexed_attribute.html", null ],
    [ "Texture", "classlagrange_1_1ui_1_1_texture.html", null ],
    [ "ToolbarPanel", "structlagrange_1_1ui_1_1_toolbar_panel.html", null ],
    [ "Tools", "classlagrange_1_1ui_1_1_tools.html", null ],
    [ "Texture::Transform", "structlagrange_1_1ui_1_1_texture_1_1_transform.html", null ],
    [ "Transform", "structlagrange_1_1ui_1_1_transform.html", null ],
    [ "TransformChangedEvent", "structlagrange_1_1ui_1_1_transform_changed_event.html", null ],
    [ "TranslateToolTag", "structlagrange_1_1ui_1_1_translate_tool_tag.html", null ],
    [ "TreeNode", "structlagrange_1_1ui_1_1_tree_node.html", null ],
    [ "true_type", null, [
      [ "is_mesh_helper< MeshType, typename Void< typename MeshType::VertexArray, typename MeshType::FacetArray >::type >", "structlagrange_1_1_mesh_trait_helper_1_1is__mesh__helper_3_01_mesh_type_00_01typename_01_void_3_189721d847f0585e54612704ceb864c0.html", null ],
      [ "is_mesh_smart_ptr_helper< MeshTypePtr, typename Void< typename MeshTypePtr::element_type, typename MeshTypePtr::element_type::VertexArray, typename MeshTypePtr::element_type::FacetArray >::type >", "structlagrange_1_1_mesh_trait_helper_1_1is__mesh__smart__ptr__helper_3_01_mesh_type_ptr_00_01typdd3a1b441f06e428de34247e1df62704.html", null ]
    ] ],
    [ "type_traits< T >", "structlagrange_1_1ui_1_1type__traits.html", null ],
    [ "type_traits< double >", "structlagrange_1_1ui_1_1type__traits_3_01double_01_4.html", null ],
    [ "type_traits< float >", "structlagrange_1_1ui_1_1type__traits_3_01float_01_4.html", null ],
    [ "type_traits< int16_t >", "structlagrange_1_1ui_1_1type__traits_3_01int16__t_01_4.html", null ],
    [ "type_traits< int32_t >", "structlagrange_1_1ui_1_1type__traits_3_01int32__t_01_4.html", null ],
    [ "type_traits< int8_t >", "structlagrange_1_1ui_1_1type__traits_3_01int8__t_01_4.html", null ],
    [ "type_traits< uint16_t >", "structlagrange_1_1ui_1_1type__traits_3_01uint16__t_01_4.html", null ],
    [ "type_traits< uint32_t >", "structlagrange_1_1ui_1_1type__traits_3_01uint32__t_01_4.html", null ],
    [ "type_traits< uint8_t >", "structlagrange_1_1ui_1_1type__traits_3_01uint8__t_01_4.html", null ],
    [ "UIPanel", "structlagrange_1_1ui_1_1_u_i_panel.html", null ],
    [ "UIWidget", "classlagrange_1_1ui_1_1_u_i_widget.html", null ],
    [ "UVDistortionOptions", "structlagrange_1_1_u_v_distortion_options.html", null ],
    [ "value_field< T >", "structlagrange_1_1ui_1_1utils_1_1value__field.html", null ],
    [ "value_field< double >", "structlagrange_1_1ui_1_1utils_1_1value__field_3_01double_01_4.html", null ],
    [ "value_field< float >", "structlagrange_1_1ui_1_1utils_1_1value__field_3_01float_01_4.html", null ],
    [ "value_field< int >", "structlagrange_1_1ui_1_1utils_1_1value__field_3_01int_01_4.html", null ],
    [ "value_ptr< T, Cloner, Deleter >", "classlagrange_1_1value__ptr.html", null ],
    [ "value_ptr< AttributeManager >", "classlagrange_1_1value__ptr.html", null ],
    [ "value_ptr< lagrange::winding::FastWindingNumber::Impl >", "classlagrange_1_1value__ptr.html", null ],
    [ "VAO", "structlagrange_1_1ui_1_1_v_a_o.html", null ],
    [ "vector", null, [
      [ "SmallVector< Scalar, 3 >", "classlagrange_1_1_small_vector.html", null ],
      [ "SmallVector< T, N >", "classlagrange_1_1_small_vector.html", null ]
    ] ],
    [ "Vector4f", null, [
      [ "Color", "classlagrange_1_1ui_1_1_color.html", null ]
    ] ],
    [ "VerboseTimer", "classlagrange_1_1_verbose_timer.html", null ],
    [ "VertexBuffer", "structlagrange_1_1ui_1_1_vertex_buffer.html", null ],
    [ "VertexData", "structlagrange_1_1ui_1_1_vertex_data.html", null ],
    [ "VertexNormalOptions", "structlagrange_1_1_vertex_normal_options.html", null ],
    [ "VertexValenceOptions", "structlagrange_1_1_vertex_valence_options.html", null ],
    [ "Viewer", "classlagrange_1_1ui_1_1_viewer.html", null ],
    [ "ViewportComponent", "structlagrange_1_1ui_1_1_viewport_component.html", [
      [ "ShadowmappingViewport", "structlagrange_1_1ui_1_1_shadowmapping_viewport.html", null ]
    ] ],
    [ "ViewportPanel", "structlagrange_1_1ui_1_1_viewport_panel.html", null ],
    [ "Camera::ViewportTransform", "structlagrange_1_1ui_1_1_camera_1_1_viewport_transform.html", null ],
    [ "Void< Ts >", "structlagrange_1_1_mesh_trait_helper_1_1_void.html", null ],
    [ "VolumeToMeshOptions", "structlagrange_1_1volume_1_1_volume_to_mesh_options.html", null ],
    [ "weak_ptr< T >", "classlagrange_1_1internal_1_1weak__ptr.html", null ],
    [ "weak_ptr< lagrange::AttributeBase >", "classlagrange_1_1internal_1_1weak__ptr.html", null ],
    [ "WindowCloseEvent", "structlagrange_1_1ui_1_1_window_close_event.html", null ],
    [ "WindowDropEvent", "structlagrange_1_1ui_1_1_window_drop_event.html", null ],
    [ "Viewer::WindowOptions", "structlagrange_1_1ui_1_1_viewer_1_1_window_options.html", null ],
    [ "WindowResizeEvent", "structlagrange_1_1ui_1_1_window_resize_event.html", null ],
    [ "WindowSize", "structlagrange_1_1ui_1_1_window_size.html", null ]
];