name: github pages

on:
  push:
    branches:
      - docs

jobs:
  build-deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.1
        with:
          pixi-version: v0.55.0

      - name: Build website
        shell: bash -l {0}
        run: |
          git clone --depth 1 https://github.com/adobe/lagrange.git ./lagrange_tmp
          pixi run python generate.py ./lagrange_tmp
          pixi run mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./site

      - name: Check links
        shell: bash -l {0}
        run: pixi run linkchecker site/index.html
